using System.Text.Json;
using System.Text.Json.Serialization;
using OSDC.DotnetLibraries.Drilling.Surveying;
using OSDC.DotnetLibraries.General.Math;

namespace OSDC.DotnetLibraries.Drilling.Surveying.UnitTest
{
    /// <summary>
    /// Golden vector tests for the closed form constant curvature and toolface construction used by
    /// <see cref="SurveyPoint.CompleteCDTSIA(General.Common.CurvilinearPoint3D)"/>.
    ///
    /// The vectors in ctc_reference_vectors.json were generated by an independent Python reference
    /// implementation in float64 and carry their own declared tolerances: 1e-12 relative on the
    /// curvature, 1e-12 rad on the toolface angle, 1e-13 relative on the build up rate and the effective
    /// sine, 1e-12 rad on interior attitudes and 1e-8 m on position. The position tolerance is the looser
    /// one because it depends on the quadrature rule, whereas the curve defining parameters are closed
    /// form and agree to near machine precision.
    /// </summary>
    public class CtcVectorTests
    {
        private const double TwoPi = 2.0 * System.Math.PI;

        private static VectorFile LoadVectors()
        {
            string path = Path.Combine(TestContext.CurrentContext.TestDirectory, "ctc_reference_vectors.json");
            Assert.That(File.Exists(path), Is.True, $"Reference vector file not found at {path}.");
            VectorFile? file = JsonSerializer.Deserialize<VectorFile>(File.ReadAllText(path));
            Assert.That(file, Is.Not.Null);
            return file!;
        }

        private static double WrapToPi(double angle)
        {
            double wrapped = System.Math.IEEERemainder(angle, TwoPi);
            if (wrapped <= -System.Math.PI)
            {
                wrapped += TwoPi;
            }
            return wrapped;
        }

        private static void AssertRelative(double actual, double expected, double tolerance, string what, List<string> failures, double absoluteFloor = 0.0)
        {
            double error = System.Math.Abs(actual - expected);
            if (!(error <= tolerance * System.Math.Abs(expected) + absoluteFloor))
            {
                failures.Add($"{what}: expected {expected:R}, got {actual:R}, absolute error {error:E3}");
            }
        }

        private static void AssertAbsolute(double actual, double expected, double tolerance, string what, List<string> failures)
        {
            double error = System.Math.Abs(actual - expected);
            if (!(error <= tolerance))
            {
                failures.Add($"{what}: expected {expected:R}, got {actual:R}, absolute error {error:E3}");
            }
        }

        /// <summary>
        /// The 220 inverse cases: curve defining parameters, interior attitudes and end position of the
        /// constant curvature and toolface curve through two survey stations.
        /// </summary>
        [Test]
        public void Test30CompleteCDTSIAMatchesReferenceVectorsInverse()
        {
            VectorFile file = LoadVectors();
            List<string> failures = new();

            foreach (InverseCase c in file.InverseCases!)
            {
                CaseInput i = c.Input!;
                InverseExpected e = c.Expected!;
                string name = c.Name ?? "?";

                SurveyPoint start = new SurveyPoint()
                {
                    X = i.N0,
                    Y = i.E0,
                    Z = i.V0,
                    Abscissa = 0.0,
                    Inclination = i.Theta0,
                    Azimuth = i.Alpha0
                };
                SurveyPoint next = new SurveyPoint()
                {
                    Abscissa = i.DMD,
                    Inclination = i.Theta1,
                    Azimuth = i.Alpha1
                };

                if (!start.CompleteCDTSIA(next, i.Branch))
                {
                    failures.Add($"{name}: CompleteCDTSIA returned false.");
                    continue;
                }

                AssertRelative(next.Curvature!.Value, e.Kappa, 1e-12, $"{name}: curvature", failures);
                AssertAbsolute(next.Toolface!.Value, e.Phi, 1e-12, $"{name}: toolface angle", failures);
                AssertRelative(next.BUR!.Value, e.Beta, 1e-13, $"{name}: build up rate", failures);
                AssertRelative(SurveyPoint.EffectiveSineCDT(i.Theta0, i.Theta1), e.G, 1e-13, $"{name}: effective sine", failures);
                AssertRelative(SurveyPoint.LogTanRatioCDT(i.Theta0, i.Theta1), e.A, 1e-13, $"{name}: log tan ratio", failures);

                // The azimuth change, and therefore the turn parameter and the two turn rates, can only be
                // recovered from the reported azimuths to the resolution of a double at the magnitude of
                // the azimuth itself. When the turn is very small against that magnitude the recoverable
                // relative precision degrades accordingly, so the comparison carries a matching absolute
                // floor. The bundled Python reference loses exactly the same digits on those cases.
                double azimuthResolution = 4.0 * System.Math.ScaleB(1.0, -52) * System.Math.Max(1.0, System.Math.Abs(i.Alpha0));
                double turnFloor = e.G * azimuthResolution / i.DMD;
                double turn = next.TUR!.Value * System.Math.Sin(i.Theta1);
                AssertRelative(turn, e.T, 1e-12, $"{name}: turn parameter", failures, turnFloor);
                AssertRelative(turn / System.Math.Sin(i.Theta0), e.Tau0, 1e-12, $"{name}: turn rate at start", failures, turnFloor / System.Math.Sin(i.Theta0));
                AssertRelative(next.TUR!.Value, e.Tau1, 1e-12, $"{name}: turn rate at end", failures, turnFloor / System.Math.Sin(i.Theta1));

                AssertAbsolute(WrapToPi(i.Alpha1 - i.Alpha0) + TwoPi * i.Branch, e.DAlpha, 1e-12, $"{name}: azimuth change", failures);

                AssertAbsolute(next.X!.Value, e.N1, 1e-8, $"{name}: north", failures);
                AssertAbsolute(next.Y!.Value, e.E1, 1e-8, $"{name}: east", failures);
                AssertAbsolute(next.Z!.Value, e.V1, 1e-8, $"{name}: vertical", failures);

                foreach (InteriorPoint pt in e.Interior!)
                {
                    if (!start.AttitudeAtAbscissaCDT(next, pt.S, out double inclination, out double azimuth, i.Branch))
                    {
                        failures.Add($"{name}: AttitudeAtAbscissaCDT returned false at s = {pt.S:R}.");
                        continue;
                    }
                    AssertAbsolute(inclination, pt.Theta, 1e-12, $"{name}: inclination at s = {pt.S:R}", failures);
                    AssertAbsolute(azimuth, pt.Alpha, 1e-12, $"{name}: azimuth at s = {pt.S:R}", failures);
                }
            }

            Assert.That(failures, Is.Empty,
                $"{failures.Count} check(s) failed over {file.InverseCases!.Count} inverse cases. " +
                string.Join(" | ", failures.Take(10)));
        }

        /// <summary>
        /// The 36 forward cases. Each one also serves as a round trip test: propagating a curvature, a
        /// toolface angle and a curve length forward and feeding the resulting station back through
        /// CompleteCDTSIA must return the curvature and the toolface angle it started from.
        /// </summary>
        [Test]
        public void Test31CompleteCDTSIAMatchesReferenceVectorsForwardAndRoundTrips()
        {
            VectorFile file = LoadVectors();
            List<string> failures = new();

            foreach (ForwardCase c in file.ForwardCases!)
            {
                ForwardInput i = c.Input!;
                ForwardExpected e = c.Expected!;
                string name = c.Name ?? "?";

                double bur = i.Kappa * System.Math.Cos(i.Phi);
                double turn = i.Kappa * System.Math.Sin(i.Phi);
                double theta1 = i.Theta0 + bur * i.L;
                double alpha1 = i.Alpha0 + turn * i.L / SurveyPoint.EffectiveSineCDT(i.Theta0, theta1);

                AssertAbsolute(theta1, e.Theta1, 1e-12, $"{name}: end inclination", failures);
                AssertAbsolute(alpha1, e.Alpha1, 1e-12, $"{name}: end azimuth", failures);

                SurveyPoint start = new SurveyPoint()
                {
                    X = i.N0,
                    Y = i.E0,
                    Z = i.V0,
                    Abscissa = 0.0,
                    Inclination = i.Theta0,
                    Azimuth = i.Alpha0
                };
                SurveyPoint next = new SurveyPoint()
                {
                    Abscissa = i.L,
                    Inclination = theta1,
                    Azimuth = alpha1
                };

                // The forward propagation produced a continuous azimuth, which may well have turned by
                // more than half a turn, so it must not be unwrapped on the way back in.
                if (!start.CompleteCDTSIA(next, 0, false))
                {
                    failures.Add($"{name}: CompleteCDTSIA returned false.");
                    continue;
                }

                AssertAbsolute(next.X!.Value, e.N1, 1e-8, $"{name}: north", failures);
                AssertAbsolute(next.Y!.Value, e.E1, 1e-8, $"{name}: east", failures);
                AssertAbsolute(next.Z!.Value, e.V1, 1e-8, $"{name}: vertical", failures);

                AssertRelative(next.Curvature!.Value, i.Kappa, 1e-12, $"{name}: round trip curvature", failures);
                AssertAbsolute(next.Toolface!.Value, WrapToPi(i.Phi), 1e-12, $"{name}: round trip toolface angle", failures);
            }

            Assert.That(failures, Is.Empty,
                $"{failures.Count} check(s) failed over {file.ForwardCases!.Count} forward cases. " +
                string.Join(" | ", failures.Take(10)));
        }

        /// <summary>
        /// The effective sine is a weighted mean of the sine over the segment, so it must always lie
        /// between the extreme values of the sine on that interval, and it must tend to sin(i0) as the
        /// two inclinations meet. That bound is what lets the zero build up case be a limit of the general
        /// formula rather than a separate branch.
        /// </summary>
        [Test]
        public void Test32EffectiveSineIsBoundedByTheSineOverTheSegment()
        {
            Random random = new Random(20240917);
            for (int k = 0; k < 20000; k++)
            {
                double i0 = 1e-3 + (System.Math.PI - 2e-3) * random.NextDouble();
                double i1 = 1e-3 + (System.Math.PI - 2e-3) * random.NextDouble();
                double g = SurveyPoint.EffectiveSineCDT(i0, i1);

                double low = System.Math.Min(i0, i1);
                double high = System.Math.Max(i0, i1);
                double minSine = System.Math.Min(System.Math.Sin(low), System.Math.Sin(high));
                double maxSine = low <= System.Math.PI / 2.0 && high >= System.Math.PI / 2.0
                    ? 1.0
                    : System.Math.Max(System.Math.Sin(low), System.Math.Sin(high));

                Assert.That(g, Is.GreaterThanOrEqualTo(minSine - 1e-12).And.LessThanOrEqualTo(maxSine + 1e-12),
                    $"effective sine {g:R} outside [{minSine:R}, {maxSine:R}] for inclinations {i0:R} and {i1:R}");
            }
        }

        /// <summary>
        /// The effective sine must stay continuous as the two inclinations meet, with no threshold to
        /// cross, which is what removes the build up rate branch from the curve defining parameters.
        /// </summary>
        [TestCase(0.2)]
        [TestCase(1.0)]
        [TestCase(1.5707963267948966)]
        [TestCase(2.9)]
        public void Test33EffectiveSineIsContinuousAtZeroBuildUp(double inclination)
        {
            double reference = System.Math.Sin(inclination);
            foreach (double d in new[] { 1e-1, 1e-3, 1e-5, 1e-7, 1e-9, 1e-11, 1e-13, 0.0 })
            {
                double g = SurveyPoint.EffectiveSineCDT(inclination, inclination + d);
                Assert.That(System.Math.Abs(g - reference), Is.LessThanOrEqualTo(d + 1e-14),
                    $"effective sine jumped at d = {d:R}: {g:R} against sin = {reference:R}");
            }
        }

        /// <summary>
        /// Branch 0 is the minimum dogleg solution, and the vertical is the same on every branch.
        /// </summary>
        [Test]
        public void Test34AzimuthBranchZeroIsTheMinimumDoglegSolution()
        {
            SurveyPoint start = new SurveyPoint()
            {
                X = 0.0,
                Y = 0.0,
                Z = 0.0,
                Abscissa = 0.0,
                Inclination = 0.05,
                Azimuth = 1.0
            };

            SurveyPoint reference = new SurveyPoint() { Abscissa = 300.0, Inclination = 0.07, Azimuth = 2.2 };
            Assert.That(start.CompleteCDTSIA(reference), Is.True);
            double curvature0 = reference.Curvature!.Value;
            double vertical0 = reference.Z!.Value;

            foreach (int branch in new[] { -2, -1, 1, 2 })
            {
                SurveyPoint other = new SurveyPoint() { Abscissa = 300.0, Inclination = 0.07, Azimuth = 2.2 };
                Assert.That(start.CompleteCDTSIA(other, branch), Is.True);
                Assert.That(other.Curvature!.Value, Is.GreaterThan(curvature0),
                    $"branch {branch} should have a larger curvature than branch 0");
                Assert.That(other.Z!.Value, Is.EqualTo(vertical0).Within(1e-12),
                    $"branch {branch} changed the vertical");
            }
        }

        /// <summary>
        /// WrapToPi must map exactly onto (-PI, PI] and must not lose the last bits of a small difference.
        /// </summary>
        [Test]
        public void Test35WrapToPiIsExact()
        {
            Assert.That(SurveyPoint.WrapToPi(-0.001), Is.EqualTo(-0.001));
            Assert.That(SurveyPoint.WrapToPi(0.001), Is.EqualTo(0.001));
            Assert.That(SurveyPoint.WrapToPi(-System.Math.PI), Is.EqualTo(System.Math.PI).Within(1e-15));

            Random random = new Random(13579);
            for (int k = 0; k < 10000; k++)
            {
                double a = (random.NextDouble() - 0.5) * 40.0;
                double w = SurveyPoint.WrapToPi(a);
                Assert.That(w, Is.GreaterThan(-System.Math.PI - 1e-15).And.LessThanOrEqualTo(System.Math.PI + 1e-15));
                double turns = (a - w) / TwoPi;
                Assert.That(System.Math.Abs(turns - System.Math.Round(turns)), Is.LessThan(1e-12),
                    $"wrap({a:R}) = {w:R} did not differ from the input by a whole number of turns");
            }
        }

        /// <summary>
        /// The target point solve. Given a fully defined start station and a target coordinate it must
        /// find the curvature, toolface angle and length of the constant curvature and toolface curve
        /// that reaches it, including where that curve runs into vertical and continues along its
        /// tangent. The parameters it reports must be the exact ones, so propagating them forward has to
        /// land back on the target.
        /// </summary>
        [Test]
        public void Test36CompleteCDTXYZReachesTheTargetAndReportsExactParameters()
        {
            const double toolfaceEpsilon = 1e-3;
            Random random = new Random(918273645);
            List<string> failures = new();
            int total = 0;
            int throughVertical = 0;
            double worst = 0.0;

            for (int i = 0; i < 40; i++)
            {
                SurveyPoint start = new SurveyPoint()
                {
                    X = 0.0,
                    Y = 0.0,
                    Z = 0.0,
                    Abscissa = 0.0,
                    Inclination = 1e-3 + (System.Math.PI - 2e-3) * random.NextDouble(),
                    Azimuth = TwoPi * random.NextDouble()
                };

                for (int j = 0; j < 40; j++)
                {
                    double curvature = 1e-6 + 0.02 * random.NextDouble();
                    double length = System.Math.Min(1000.0, System.Math.PI / curvature) * random.NextDouble();
                    double toolface = toolfaceEpsilon + (TwoPi - 2.0 * toolfaceEpsilon) * random.NextDouble();

                    SurveyPoint forward = new SurveyPoint() { Abscissa = length };
                    if (!start.CompleteCDTSDT(forward, curvature, toolface))
                    {
                        continue;
                    }
                    total++;
                    if (!(start.Inclination!.Value + curvature * System.Math.Cos(toolface) * length > 0.0 &&
                          start.Inclination.Value + curvature * System.Math.Cos(toolface) * length < System.Math.PI))
                    {
                        throughVertical++;
                    }

                    SurveyPoint recovered = new SurveyPoint() { X = forward.X, Y = forward.Y, Z = forward.Z };
                    if (!start.CompleteCDTXYZ(recovered) || recovered.Abscissa == null || recovered.Curvature == null)
                    {
                        failures.Add($"case {i}/{j}: the target point solve did not return a solution.");
                        continue;
                    }

                    // A straight segment has no toolface angle, and nothing to propagate.
                    if (recovered.Toolface == null)
                    {
                        continue;
                    }

                    SurveyPoint check = new SurveyPoint() { Abscissa = recovered.Abscissa };
                    if (!start.CompleteCDTSDT(check, recovered.Curvature.Value, recovered.Toolface.Value) ||
                        check.X == null || check.Y == null || check.Z == null)
                    {
                        failures.Add($"case {i}/{j}: the reported parameters could not be propagated.");
                        continue;
                    }
                    double error = System.Math.Max(System.Math.Abs(check.X.Value - forward.X!.Value),
                        System.Math.Max(System.Math.Abs(check.Y.Value - forward.Y!.Value),
                                        System.Math.Abs(check.Z.Value - forward.Z!.Value)));
                    worst = System.Math.Max(worst, error);
                    if (!(error <= 1e-6))
                    {
                        failures.Add($"case {i}/{j}: the reported curve misses the target by {error:E3} m.");
                    }
                }
            }

            Assert.That(total, Is.GreaterThan(1000), "the generator produced too few usable cases");
            Assert.That(throughVertical, Is.GreaterThan(0), "no case exercised a curve running into vertical");
            Assert.That(failures, Is.Empty,
                $"{failures.Count} of {total} target point solves failed (worst miss {worst:E3} m). " +
                string.Join(" | ", failures.Take(8)));
        }

        /// <summary>
        /// For a target lying in the vertical plane through the start azimuth the solve is closed form:
        /// the ratio of horizontal to vertical offset is the tangent of the mean inclination, so the end
        /// inclination is 2*atan2(dHorizontal, dVertical) - inclinationStart exactly. This is the seed
        /// the general solve starts from, so it is worth pinning down on its own.
        /// </summary>
        [TestCase(0.30, 0.004, 150.0, 0.0)]
        [TestCase(1.10, 0.003, 220.0, 0.0)]
        [TestCase(1.90, 0.005, 100.0, System.Math.PI)]
        public void Test37PlanarTargetSolveIsClosedForm(double inclinationStart, double curvature, double length, double toolface)
        {
            SurveyPoint start = new SurveyPoint()
            {
                X = 0.0,
                Y = 0.0,
                Z = 0.0,
                Abscissa = 0.0,
                Inclination = inclinationStart,
                Azimuth = 0.0
            };
            SurveyPoint forward = new SurveyPoint() { Abscissa = length };
            Assert.That(start.CompleteCDTSDT(forward, curvature, toolface), Is.True);

            double horizontal = System.Math.Sqrt(forward.X!.Value * forward.X.Value + forward.Y!.Value * forward.Y.Value);
            double closedForm = 2.0 * System.Math.Atan2(horizontal, forward.Z!.Value) - inclinationStart;

            Assert.That(closedForm, Is.EqualTo(forward.Inclination!.Value).Within(1e-12),
                "the closed form planar end inclination did not reproduce the propagated one");
        }

        private static double Sq(double x) => x * x;

        /// <summary>
        /// Interpolation along a constant curvature and toolface segment. The properties that matter are
        /// that it carries its own end stations unaltered, that the measured depth never goes backwards,
        /// and that a densified polyline converges on the length of the segment.
        /// </summary>
        [Test]
        public void Test38InterpolateAtAbscissaCDTIsExactAndConsistent()
        {
            const TrajectoryCalculationType Ctc = TrajectoryCalculationType.ConstantCurvatureAndToolfaceMethod;
            const int steps = 60;
            Random random = new Random(20260914);
            List<string> failures = new();
            int segments = 0;
            int throughVertical = 0;

            for (int k = 0; k < 400; k++)
            {
                double inclinationStart = 0.03 + (System.Math.PI - 0.06) * random.NextDouble();
                double azimuthStart = TwoPi * random.NextDouble();
                double curvature = 1e-5 + 0.01 * random.NextDouble();
                double toolface = -System.Math.PI + TwoPi * random.NextDouble();
                double length = 5.0 + 400.0 * random.NextDouble();
                double measuredDepthStart = 1000.0;

                SurveyPoint start = new SurveyPoint()
                {
                    X = 0.0,
                    Y = 0.0,
                    Z = 0.0,
                    Abscissa = measuredDepthStart,
                    Inclination = inclinationStart,
                    Azimuth = azimuthStart
                };
                SurveyPoint next = new SurveyPoint() { Abscissa = measuredDepthStart + length };
                if (!start.CompleteCDTSDT(next, curvature, toolface))
                {
                    continue;
                }
                segments++;
                double rawEndInclination = inclinationStart + curvature * System.Math.Cos(toolface) * length;
                if (!(rawEndInclination > 0.0 && rawEndInclination < System.Math.PI))
                {
                    throughVertical++;
                }

                SurveyPoint[] points = new SurveyPoint[steps + 1];
                bool complete = true;
                for (int j = 0; j <= steps; j++)
                {
                    // Deliberately the natural densification expression, whose last step can land a few
                    // units in the last place beyond the end station.
                    double measuredDepth = measuredDepthStart + length * j / (double)steps;
                    SurveyPoint point = new SurveyPoint();
                    if (!start.InterpolateAtAbscissa(next, measuredDepth, point, Ctc) ||
                        point.X == null || point.Y == null || point.Z == null ||
                        double.IsNaN(point.X.Value) || double.IsNaN(point.Y.Value) || double.IsNaN(point.Z.Value))
                    {
                        failures.Add($"segment {k}: interpolation failed at fraction {j / (double)steps:F3}.");
                        complete = false;
                        break;
                    }
                    points[j] = point;
                }
                if (!complete)
                {
                    continue;
                }

                if (!(System.Math.Abs(points[0].X!.Value - start.X!.Value) <= 1e-12 &&
                      System.Math.Abs(points[0].Z!.Value - start.Z!.Value) <= 1e-12))
                {
                    failures.Add($"segment {k}: the start station was not reproduced.");
                }
                if (!(System.Math.Abs(points[steps].X!.Value - next.X!.Value) <= 1e-12 &&
                      System.Math.Abs(points[steps].Z!.Value - next.Z!.Value) <= 1e-12))
                {
                    failures.Add($"segment {k}: the end station was not reproduced.");
                }

                for (int j = 1; j <= steps; j++)
                {
                    if (points[j].Abscissa!.Value < points[j - 1].Abscissa!.Value - 1e-12)
                    {
                        failures.Add($"segment {k}: measured depth went backwards at step {j}.");
                        break;
                    }
                }

                // With this many chords the shortfall against the segment length is the geometric chord
                // against arc difference and nothing more.
                double polyline = 0.0;
                for (int j = 1; j <= steps; j++)
                {
                    polyline += System.Math.Sqrt(
                        Sq(points[j].X!.Value - points[j - 1].X!.Value) +
                        Sq(points[j].Y!.Value - points[j - 1].Y!.Value) +
                        Sq(points[j].Z!.Value - points[j - 1].Z!.Value));
                }
                if (!(polyline <= length + 1e-9 && polyline >= length * (1.0 - 1e-3)))
                {
                    failures.Add($"segment {k}: densified length {polyline:F6} against a segment of {length:F6}.");
                }
            }

            Assert.That(segments, Is.GreaterThan(300), "too few usable segments");
            Assert.That(throughVertical, Is.GreaterThan(0), "no segment exercised a curve running into vertical");
            Assert.That(failures, Is.Empty, $"{failures.Count} failure(s). " + string.Join(" | ", failures.Take(8)));
        }

        /// <summary>
        /// Interpolation must not depend on the far station carrying the curve defining parameters: two
        /// stations and the distance between them determine the curve on their own.
        /// </summary>
        [Test]
        public void Test39InterpolateAtAbscissaCDTDoesNotRequireCarriedParameters()
        {
            const TrajectoryCalculationType Ctc = TrajectoryCalculationType.ConstantCurvatureAndToolfaceMethod;
            SurveyPoint start = new SurveyPoint()
            {
                X = 0.0,
                Y = 0.0,
                Z = 0.0,
                Abscissa = 1000.0,
                Inclination = 0.30,
                Azimuth = 1.00
            };
            SurveyPoint reference = new SurveyPoint() { Abscissa = 1040.0, Inclination = 0.55, Azimuth = 1.45 };
            Assert.That(start.CompleteCDTSIA(reference), Is.True);

            SurveyPoint withParameters = new SurveyPoint();
            Assert.That(start.InterpolateAtAbscissa(reference, 1020.0, withParameters, Ctc), Is.True);

            // The same far station, stripped of everything but its position and its attitude.
            SurveyPoint stripped = new SurveyPoint()
            {
                Abscissa = reference.Abscissa,
                Inclination = reference.Inclination,
                Azimuth = reference.Azimuth,
                X = reference.X,
                Y = reference.Y,
                Z = reference.Z
            };
            SurveyPoint withoutParameters = new SurveyPoint();
            Assert.That(start.InterpolateAtAbscissa(stripped, 1020.0, withoutParameters, Ctc), Is.True,
                "interpolation refused a far station that did not carry a curvature and toolface angle");

            Assert.That(withoutParameters.X!.Value, Is.EqualTo(withParameters.X!.Value).Within(1e-9));
            Assert.That(withoutParameters.Y!.Value, Is.EqualTo(withParameters.Y!.Value).Within(1e-9));
            Assert.That(withoutParameters.Z!.Value, Is.EqualTo(withParameters.Z!.Value).Within(1e-9));
            Assert.That(withoutParameters.Inclination!.Value, Is.EqualTo(withParameters.Inclination!.Value).Within(1e-12));
        }

        /// <summary>
        /// The turn rate reported at an interpolated point is signed: a left hand turn must not be
        /// reported as a right hand one.
        /// </summary>
        [Test]
        public void Test40InterpolatedTurnRateIsSigned()
        {
            const TrajectoryCalculationType Ctc = TrajectoryCalculationType.ConstantCurvatureAndToolfaceMethod;
            SurveyPoint start = new SurveyPoint()
            {
                X = 0.0,
                Y = 0.0,
                Z = 0.0,
                Abscissa = 1000.0,
                Inclination = 0.80,
                Azimuth = 2.00
            };
            // The azimuth decreases over the segment, so this is a left hand turn.
            SurveyPoint next = new SurveyPoint() { Abscissa = 1060.0, Inclination = 1.00, Azimuth = 1.40 };
            Assert.That(start.CompleteCDTSIA(next), Is.True);
            Assert.That(next.Toolface!.Value, Is.LessThan(0.0), "the segment should have a negative toolface angle");
            Assert.That(next.TUR!.Value, Is.LessThan(0.0), "the segment should have a negative turn rate");

            SurveyPoint middle = new SurveyPoint();
            Assert.That(start.InterpolateAtAbscissa(next, 1030.0, middle, Ctc), Is.True);
            Assert.That(middle.TUR, Is.Not.Null);
            Assert.That(middle.TUR!.Value, Is.LessThan(0.0),
                "the interpolated turn rate reported a right hand turn on a left hand turn");
        }

        /// <summary>
        /// Composite Simpson on the exact constant build and turn integrand, used as an independent
        /// reference for the closed form. Both angles are linear in the along hole distance, so the
        /// integrand is smooth and this converges quickly.
        /// </summary>
        private static void ReferenceBuildAndTurn(double inclinationStart, double azimuthStart, double bur, double tur, double length, out double dNorth, out double dEast, out double dVertical)
        {
            const int panels = 20000;
            double h = length / panels;
            dNorth = 0.0;
            dEast = 0.0;
            dVertical = 0.0;
            for (int i = 0; i <= panels; i++)
            {
                double s = i * h;
                double weight = (i == 0 || i == panels) ? 1.0 : (i % 2 == 1 ? 4.0 : 2.0);
                double inclination = inclinationStart + bur * s;
                double azimuth = azimuthStart + tur * s;
                dNorth += weight * System.Math.Sin(inclination) * System.Math.Cos(azimuth);
                dEast += weight * System.Math.Sin(inclination) * System.Math.Sin(azimuth);
                dVertical += weight * System.Math.Cos(inclination);
            }
            double scale = h / 3.0;
            dNorth *= scale;
            dEast *= scale;
            dVertical *= scale;
        }

        /// <summary>
        /// The constant build and turn construction against an independent integration of its own
        /// integrand, including the cases where the build up rate equals plus or minus the turn rate and
        /// where either vanishes. Those are removable singularities of the textbook form, which divides
        /// by the sum and the difference of the two rates; writing the integrals as
        /// length*sin(mean phase)*sinc(half swept angle) removes the division altogether, so the
        /// neighbourhood of those points is no longer a place where digits are lost.
        /// </summary>
        [TestCase(2e-3, 7e-4, "general")]
        [TestCase(2e-3, 2e-3, "build up rate equals turn rate")]
        [TestCase(2e-3, 1.999999e-3, "just off equal rates")]
        [TestCase(2e-3, 1.999999999e-3, "very close to equal rates")]
        [TestCase(2e-3, -2e-3, "build up rate equals minus turn rate")]
        [TestCase(2e-3, -1.999999999e-3, "very close to opposite rates")]
        [TestCase(0.0, 1e-3, "no build up")]
        [TestCase(1e-12, 1e-3, "almost no build up")]
        [TestCase(1e-11, 1e-11, "almost straight")]
        [TestCase(1.5e-3, -4e-3, "strongly turning")]
        public void Test41CompleteBTSIAMatchesAnIndependentIntegration(double bur, double tur, string what)
        {
            const double inclinationStart = 0.6;
            const double azimuthStart = 1.0;
            const double length = 300.0;

            ReferenceBuildAndTurn(inclinationStart, azimuthStart, bur, tur, length,
                out double expectedNorth, out double expectedEast, out double expectedVertical);

            SurveyPoint start = new SurveyPoint()
            {
                X = 0.0,
                Y = 0.0,
                Z = 0.0,
                Abscissa = 0.0,
                Inclination = inclinationStart,
                Azimuth = azimuthStart
            };
            SurveyPoint next = new SurveyPoint()
            {
                Abscissa = length,
                Inclination = inclinationStart + bur * length,
                Azimuth = azimuthStart + tur * length
            };
            // The azimuth here is continuous by construction, so it must be used as supplied.
            Assert.That(start.CompleteBTSIA(next, 0, false), Is.True);

            Assert.That(next.X!.Value, Is.EqualTo(expectedNorth).Within(1e-9), $"north, {what}");
            Assert.That(next.Y!.Value, Is.EqualTo(expectedEast).Within(1e-9), $"east, {what}");
            Assert.That(next.Z!.Value, Is.EqualTo(expectedVertical).Within(1e-9), $"vertical, {what}");
        }

        /// <summary>
        /// A survey reports its azimuth modulo 2*PI. A small turn across north must be read as the small
        /// turn it is, not as a turn of almost a full circle the other way.
        /// </summary>
        [Test]
        public void Test42CompleteBTSIAWrapsTheAzimuthAcrossNorth()
        {
            const double inclinationStart = 0.60;
            const double azimuthStart = 6.20;
            const double length = 20.0;
            const double turn = 0.183;
            double inclinationEnd = inclinationStart + 0.02;

            SurveyPoint continuousStart = new SurveyPoint()
            {
                X = 0.0,
                Y = 0.0,
                Z = 0.0,
                Abscissa = 0.0,
                Inclination = inclinationStart,
                Azimuth = azimuthStart
            };
            SurveyPoint continuousEnd = new SurveyPoint()
            {
                Abscissa = length,
                Inclination = inclinationEnd,
                Azimuth = azimuthStart + turn
            };
            Assert.That(continuousStart.CompleteBTSIA(continuousEnd, 0, false), Is.True);

            // The same station as a survey would actually report it, past north.
            SurveyPoint wrappedStart = new SurveyPoint()
            {
                X = 0.0,
                Y = 0.0,
                Z = 0.0,
                Abscissa = 0.0,
                Inclination = inclinationStart,
                Azimuth = azimuthStart
            };
            SurveyPoint wrappedEnd = new SurveyPoint()
            {
                Abscissa = length,
                Inclination = inclinationEnd,
                Azimuth = azimuthStart + turn - 2.0 * System.Math.PI
            };
            Assert.That(wrappedStart.CompleteBTSIA(wrappedEnd), Is.True);

            Assert.That(wrappedEnd.X!.Value, Is.EqualTo(continuousEnd.X!.Value).Within(1e-12),
                "the wrapped azimuth was read as a turn the long way round");
            Assert.That(wrappedEnd.Y!.Value, Is.EqualTo(continuousEnd.Y!.Value).Within(1e-12));
            Assert.That(wrappedEnd.Z!.Value, Is.EqualTo(continuousEnd.Z!.Value).Within(1e-12));
            Assert.That(wrappedEnd.TUR!.Value, Is.EqualTo(turn / length).Within(1e-12),
                "the turn rate should be the short way round");
        }

        /// <summary>
        /// The build up and turn rates are the defining constants of a constant build and turn segment,
        /// so they are reported exactly rather than estimated by finite differences afterwards.
        /// </summary>
        [Test]
        public void Test43CompleteBTSIAReportsExactRates()
        {
            const double inclinationStart = 0.6;
            const double azimuthStart = 1.0;
            const double bur = 2e-3;
            const double tur = -7e-4;
            const double length = 300.0;

            SurveyPoint start = new SurveyPoint()
            {
                X = 0.0,
                Y = 0.0,
                Z = 0.0,
                Abscissa = 0.0,
                Inclination = inclinationStart,
                Azimuth = azimuthStart
            };
            SurveyPoint next = new SurveyPoint()
            {
                Abscissa = length,
                Inclination = inclinationStart + bur * length,
                Azimuth = azimuthStart + tur * length
            };
            Assert.That(start.CompleteBTSIA(next, 0, false), Is.True);

            Assert.That(next.BUR!.Value, Is.EqualTo(bur).Within(1e-15));
            Assert.That(next.TUR!.Value, Is.EqualTo(tur).Within(1e-15));

            // The curvature of the path at the end station, and the toolface angle there, follow from
            // the two rates. A turn towards decreasing azimuth is a left hand turn.
            double sinEnd = System.Math.Sin(next.Inclination!.Value);
            Assert.That(next.Curvature!.Value,
                Is.EqualTo(System.Math.Sqrt(bur * bur + tur * tur * sinEnd * sinEnd)).Within(1e-15));
            Assert.That(next.Toolface!.Value, Is.LessThan(0.0), "a decreasing azimuth is a left hand turn");

            // Going through the public entry point must not replace them with estimates.
            SurveyPoint viaFromSia = new SurveyPoint()
            {
                Abscissa = length,
                Inclination = next.Inclination,
                Azimuth = azimuthStart + tur * length
            };
            Assert.That(start.CompleteFromSIA(viaFromSia, TrajectoryCalculationType.ConstantBuildAndTurnMethod), Is.True);
            Assert.That(viaFromSia.BUR!.Value, Is.EqualTo(bur).Within(1e-15));
            Assert.That(viaFromSia.TUR!.Value, Is.EqualTo(tur).Within(1e-15));
        }

        /// <summary>
        /// The constant build and turn target point solve. It must reach the target, report the curve
        /// defining parameters exactly, and reach targets whose curve turns by more than half a turn,
        /// which a search over a station azimuth folded into a single revolution cannot express.
        /// </summary>
        [Test]
        public void Test44CompleteBTXYZReachesTheTargetIncludingLargeTurns()
        {
            Random random = new Random(31415);
            List<string> failures = new();
            int targets = 0;
            int beyondHalfATurn = 0;
            double worst = 0.0;

            while (targets < 400)
            {
                double inclinationStart = 0.05 + (System.Math.PI - 0.10) * random.NextDouble();
                double azimuthStart = TwoPi * random.NextDouble();
                double sweptInclination = -2.0 + 4.0 * random.NextDouble();
                double sweptAzimuth = -3.0 * System.Math.PI + 6.0 * System.Math.PI * random.NextDouble();
                double length = 2.0 + 800.0 * random.NextDouble();
                double inclinationEnd = inclinationStart + sweptInclination;
                if (inclinationEnd <= 0.05 || inclinationEnd >= System.Math.PI - 0.05)
                {
                    continue;
                }

                SurveyPoint start = new SurveyPoint()
                {
                    X = 0.0,
                    Y = 0.0,
                    Z = 0.0,
                    Abscissa = 0.0,
                    Inclination = inclinationStart,
                    Azimuth = azimuthStart
                };
                SurveyPoint forward = new SurveyPoint()
                {
                    Abscissa = length,
                    Inclination = inclinationEnd,
                    Azimuth = azimuthStart + sweptAzimuth
                };
                if (!start.CompleteBTSIA(forward, 0, false))
                {
                    continue;
                }
                targets++;
                if (System.Math.Abs(sweptAzimuth) > System.Math.PI)
                {
                    beyondHalfATurn++;
                }

                SurveyPoint recovered = new SurveyPoint() { X = forward.X, Y = forward.Y, Z = forward.Z };
                if (!start.CompleteBTXYZ(recovered) || recovered.Abscissa == null)
                {
                    failures.Add($"target {targets}: no solution was found.");
                    continue;
                }
                if (recovered.BUR == null || recovered.TUR == null)
                {
                    failures.Add($"target {targets}: the solution carried no build up or turn rate.");
                    continue;
                }

                // Propagating the recovered station must land back on the target.
                SurveyPoint check = new SurveyPoint()
                {
                    Abscissa = recovered.Abscissa,
                    Inclination = recovered.Inclination,
                    Azimuth = recovered.Azimuth
                };
                if (!start.CompleteBTSIA(check, 0, false) || check.X == null)
                {
                    failures.Add($"target {targets}: the recovered station could not be propagated.");
                    continue;
                }
                double error = System.Math.Max(System.Math.Abs(check.X.Value - forward.X!.Value),
                    System.Math.Max(System.Math.Abs(check.Y!.Value - forward.Y!.Value),
                                    System.Math.Abs(check.Z!.Value - forward.Z!.Value)));
                worst = System.Math.Max(worst, error);
                if (!(error <= 1e-6))
                {
                    failures.Add($"target {targets}: the solution misses by {error:E3} m.");
                }
            }

            Assert.That(beyondHalfATurn, Is.GreaterThan(100),
                "the generator did not produce enough targets turning beyond half a turn");
            Assert.That(failures, Is.Empty,
                $"{failures.Count} of {targets} target point solves failed (worst miss {worst:E3} m). " +
                string.Join(" | ", failures.Take(8)));
        }

        /// <summary>
        /// A target point is reached by many constant build and turn curves. The one returned must be
        /// the shortest, which is the only choice independent of which seed the search happened to start
        /// from, and on a routine target it is the curve the caller had in mind.
        /// </summary>
        [Test]
        public void Test45CompleteBTXYZReturnsTheShortestSolution()
        {
            Random random = new Random(987654321);
            List<string> failures = new();
            int targets = 0;

            while (targets < 300)
            {
                double inclinationStart = 1e-6 + (System.Math.PI - 2e-6) * random.NextDouble();
                double azimuthStart = TwoPi * random.NextDouble();
                double length = 1000.0 * random.NextDouble();
                double inclinationEnd = 1e-6 + (System.Math.PI - 2e-6) * random.NextDouble();
                double azimuthEnd = TwoPi * random.NextDouble();
                if (length < 1.0)
                {
                    continue;
                }

                SurveyPoint start = new SurveyPoint()
                {
                    X = 0.0,
                    Y = 0.0,
                    Z = 0.0,
                    Abscissa = 0.0,
                    Inclination = inclinationStart,
                    Azimuth = azimuthStart
                };
                SurveyPoint forward = new SurveyPoint()
                {
                    Abscissa = length,
                    Inclination = inclinationEnd,
                    Azimuth = azimuthEnd
                };
                if (!start.CompleteBTSIA(forward))
                {
                    continue;
                }
                targets++;

                SurveyPoint recovered = new SurveyPoint() { X = forward.X, Y = forward.Y, Z = forward.Z };
                if (!start.CompleteBTXYZ(recovered) || recovered.Abscissa == null)
                {
                    failures.Add($"target {targets}: no solution was found.");
                    continue;
                }
                // The generating curve takes the azimuth the short way round, so it is the shortest
                // solution and the solve must return it rather than some longer curve through the same
                // point.
                if (!(System.Math.Abs(recovered.Abscissa.Value - length) <= 1e-4))
                {
                    failures.Add($"target {targets}: returned a curve of {recovered.Abscissa.Value:F4} m " +
                                 $"where {length:F4} m also reaches the target.");
                }
            }

            Assert.That(failures, Is.Empty,
                $"{failures.Count} of {targets} solves did not return the shortest curve. " +
                string.Join(" | ", failures.Take(8)));
        }

        /// <summary>
        /// Interpolation along a constant build and turn segment: it must carry its own end stations
        /// unaltered, keep the measured depth increasing, report an attitude in the canonical ranges,
        /// report the defining rates of the segment exactly, and produce a densified polyline that
        /// converges on the length of the segment.
        /// </summary>
        [Test]
        public void Test46InterpolateAtAbscissaBTIsExactAndConsistent()
        {
            const TrajectoryCalculationType Bt = TrajectoryCalculationType.ConstantBuildAndTurnMethod;
            const int steps = 60;
            Random random = new Random(20260914);
            List<string> failures = new();
            int segments = 0;

            for (int k = 0; k < 400; k++)
            {
                double inclinationStart = 0.03 + (System.Math.PI - 0.06) * random.NextDouble();
                double azimuthStart = TwoPi * random.NextDouble();
                double inclinationEnd = 0.03 + (System.Math.PI - 0.06) * random.NextDouble();
                double azimuthEnd = TwoPi * random.NextDouble();
                double length = 5.0 + 400.0 * random.NextDouble();
                double measuredDepthStart = 1000.0;

                SurveyPoint start = new SurveyPoint()
                {
                    X = 0.0,
                    Y = 0.0,
                    Z = 0.0,
                    Abscissa = measuredDepthStart,
                    Inclination = inclinationStart,
                    Azimuth = azimuthStart
                };
                SurveyPoint next = new SurveyPoint()
                {
                    Abscissa = measuredDepthStart + length,
                    Inclination = inclinationEnd,
                    Azimuth = azimuthEnd
                };
                if (!start.CompleteBTSIA(next))
                {
                    continue;
                }
                segments++;
                double bur = next.BUR!.Value;
                double tur = next.TUR!.Value;

                SurveyPoint[] points = new SurveyPoint[steps + 1];
                bool complete = true;
                for (int j = 0; j <= steps; j++)
                {
                    // The natural densification expression, whose last step can land a few units in the
                    // last place beyond the end station.
                    double measuredDepth = measuredDepthStart + length * j / (double)steps;
                    SurveyPoint point = new SurveyPoint();
                    if (!start.InterpolateAtAbscissa(next, measuredDepth, point, Bt) ||
                        point.X == null || point.Y == null || point.Z == null ||
                        double.IsNaN(point.X.Value) || double.IsNaN(point.Y.Value) || double.IsNaN(point.Z.Value))
                    {
                        failures.Add($"segment {k}: interpolation failed at fraction {j / (double)steps:F3}.");
                        complete = false;
                        break;
                    }
                    points[j] = point;
                }
                if (!complete)
                {
                    continue;
                }

                if (!(System.Math.Abs(points[0].X!.Value - start.X!.Value) <= 1e-12 &&
                      System.Math.Abs(points[0].Z!.Value - start.Z!.Value) <= 1e-12))
                {
                    failures.Add($"segment {k}: the start station was not reproduced.");
                }
                if (!(System.Math.Abs(points[steps].X!.Value - next.X!.Value) <= 1e-12 &&
                      System.Math.Abs(points[steps].Z!.Value - next.Z!.Value) <= 1e-12))
                {
                    failures.Add($"segment {k}: the end station was not reproduced.");
                }

                for (int j = 0; j <= steps; j++)
                {
                    double inclination = points[j].Inclination!.Value;
                    if (inclination < -1e-12 || inclination > System.Math.PI + 1e-12)
                    {
                        failures.Add($"segment {k}: inclination {inclination:R} left [0, pi] at step {j}.");
                        break;
                    }
                    if (j > 0 && points[j].Abscissa!.Value < points[j - 1].Abscissa!.Value - 1e-12)
                    {
                        failures.Add($"segment {k}: measured depth went backwards at step {j}.");
                        break;
                    }
                    // The rates are the defining constants of the segment, so they are exact.
                    if (points[j].BUR != null && System.Math.Abs(points[j].BUR!.Value - bur) > 1e-12)
                    {
                        failures.Add($"segment {k}: build up rate drifted at step {j}.");
                        break;
                    }
                    if (points[j].TUR != null && System.Math.Abs(points[j].TUR!.Value - tur) > 1e-12)
                    {
                        failures.Add($"segment {k}: turn rate drifted at step {j}.");
                        break;
                    }
                }

                double polyline = 0.0;
                for (int j = 1; j <= steps; j++)
                {
                    polyline += System.Math.Sqrt(
                        Sq(points[j].X!.Value - points[j - 1].X!.Value) +
                        Sq(points[j].Y!.Value - points[j - 1].Y!.Value) +
                        Sq(points[j].Z!.Value - points[j - 1].Z!.Value));
                }
                if (!(polyline <= length + 1e-9 && polyline >= length * (1.0 - 1e-3)))
                {
                    failures.Add($"segment {k}: densified length {polyline:F6} against a segment of {length:F6}.");
                }
            }

            Assert.That(segments, Is.GreaterThan(300), "too few usable segments");
            Assert.That(failures, Is.Empty, $"{failures.Count} failure(s). " + string.Join(" | ", failures.Take(8)));
        }

        /// <summary>
        /// Interpolation must read the far station the same way the segment construction does, and must
        /// not depend on that station carrying the rates. Differencing the two stations directly would
        /// describe a different curve whenever the far attitude needs folding back into its canonical
        /// ranges, or the azimuth needs taking the short way round.
        /// </summary>
        [Test]
        public void Test47InterpolateAtAbscissaBTAgreesWithTheSegmentConstruction()
        {
            const TrajectoryCalculationType Bt = TrajectoryCalculationType.ConstantBuildAndTurnMethod;
            SurveyPoint start = new SurveyPoint()
            {
                X = 0.0,
                Y = 0.0,
                Z = 0.0,
                Abscissa = 1000.0,
                Inclination = 0.30,
                Azimuth = 1.00
            };

            // A far station whose inclination sits outside [0, pi], which the construction folds.
            SurveyPoint constructed = new SurveyPoint() { Abscissa = 1400.0, Inclination = -0.25, Azimuth = 1.30 };
            Assert.That(start.CompleteBTSIA(constructed), Is.True);

            SurveyPoint asSupplied = new SurveyPoint()
            {
                Abscissa = 1400.0,
                Inclination = -0.25,
                Azimuth = 1.30,
                X = constructed.X,
                Y = constructed.Y,
                Z = constructed.Z
            };

            // Interpolating right up to the far end must land where the construction put it.
            SurveyPoint atEnd = new SurveyPoint();
            Assert.That(start.InterpolateAtAbscissa(asSupplied, 1400.0, atEnd, Bt), Is.True);
            Assert.That(atEnd.X!.Value, Is.EqualTo(constructed.X!.Value).Within(1e-9));
            Assert.That(atEnd.Y!.Value, Is.EqualTo(constructed.Y!.Value).Within(1e-9));
            Assert.That(atEnd.Z!.Value, Is.EqualTo(constructed.Z!.Value).Within(1e-9));

            // Interior attitudes stay in the canonical ranges even though the far one did not.
            foreach (double fraction in new[] { 0.3, 0.6, 0.9 })
            {
                SurveyPoint inside = new SurveyPoint();
                Assert.That(start.InterpolateAtAbscissa(asSupplied, 1000.0 + 400.0 * fraction, inside, Bt), Is.True);
                Assert.That(inside.Inclination!.Value, Is.GreaterThanOrEqualTo(0.0).And.LessThanOrEqualTo(System.Math.PI));
                Assert.That(inside.Azimuth!.Value, Is.GreaterThanOrEqualTo(0.0).And.LessThan(TwoPi + 1e-12));
            }

            // A far station that carries nothing but its position and attitude must give the same answer
            // as one that carries the rates too.
            SurveyPoint reference = new SurveyPoint() { Abscissa = 1040.0, Inclination = 0.55, Azimuth = 1.45 };
            Assert.That(start.CompleteBTSIA(reference), Is.True);
            CurvilinearPoint3D plain = new CurvilinearPoint3D()
            {
                Abscissa = reference.Abscissa,
                Inclination = reference.Inclination,
                Azimuth = reference.Azimuth,
                X = reference.X,
                Y = reference.Y,
                Z = reference.Z
            };

            SurveyPoint withRates = new SurveyPoint();
            SurveyPoint withoutRates = new SurveyPoint();
            Assert.That(start.InterpolateAtAbscissa(reference, 1020.0, withRates, Bt), Is.True);
            Assert.That(start.InterpolateAtAbscissa(plain, 1020.0, withoutRates, Bt), Is.True,
                "interpolation refused a far station that did not carry the rates");
            Assert.That(withoutRates.X!.Value, Is.EqualTo(withRates.X!.Value).Within(1e-12));
            Assert.That(withoutRates.Y!.Value, Is.EqualTo(withRates.Y!.Value).Within(1e-12));
            Assert.That(withoutRates.Z!.Value, Is.EqualTo(withRates.Z!.Value).Within(1e-12));
            Assert.That(withoutRates.BUR!.Value, Is.EqualTo(withRates.BUR!.Value).Within(1e-15));
        }

        /// <summary>
        /// The dogleg angle must stay accurate for nearly parallel tangents. Taking it as the arc cosine
        /// of the dot product loses about half the available digits there, and at a dogleg of 1e-9 rad it
        /// returns nothing but noise. The half angle form used here holds to the last bit.
        /// </summary>
        [TestCase(1e-1)]
        [TestCase(1e-3)]
        [TestCase(1e-5)]
        [TestCase(1e-7)]
        [TestCase(1e-9)]
        [TestCase(1e-11)]
        public void Test48DoglegAngleIsAccurateForSmallDoglegs(double dogleg)
        {
            // Two attitudes separated by exactly this angle, in inclination alone.
            const double inclinationStart = 0.7;
            const double azimuth = 1.3;
            double computed = SurveyPoint.DoglegAngle(inclinationStart, azimuth, inclinationStart + dogleg, azimuth);
            Assert.That(computed, Is.EqualTo(dogleg).Within(1e-15 * dogleg + 1e-16),
                $"the dogleg angle lost accuracy at {dogleg:E1} rad");
        }

        /// <summary>
        /// The dogleg angle is a property of the two directions, so it cannot depend on how many whole
        /// turns the reported azimuths happen to differ by, and it is bounded so it can never produce a
        /// value that is not a number.
        /// </summary>
        [Test]
        public void Test49DoglegAngleIsWrapInvariantAndAlwaysDefined()
        {
            Random random = new Random(4711);
            for (int k = 0; k < 20000; k++)
            {
                double i1 = 1e-9 + (System.Math.PI - 2e-9) * random.NextDouble();
                double i2 = 1e-9 + (System.Math.PI - 2e-9) * random.NextDouble();
                double a1 = TwoPi * random.NextDouble();
                double a2 = TwoPi * random.NextDouble();

                double direct = SurveyPoint.DoglegAngle(i1, a1, i2, a2);
                Assert.That(double.IsNaN(direct), Is.False, "the dogleg angle was not a number");
                Assert.That(direct, Is.GreaterThanOrEqualTo(0.0).And.LessThanOrEqualTo(System.Math.PI + 1e-12));

                int turns = random.Next(-3, 4);
                double wrapped = SurveyPoint.DoglegAngle(i1, a1, i2, a2 + TwoPi * turns);
                Assert.That(wrapped, Is.EqualTo(direct).Within(1e-12),
                    "the dogleg angle changed when the azimuth was shifted by whole turns");
            }
        }

        /// <summary>
        /// The circular arc target point solve. A circular arc leaving a known tangent and passing
        /// through a known point is fully determined, because the chord bisects the angle between the
        /// tangents at its two ends, so this is closed form and must recover the generating arc exactly.
        /// </summary>
        [Test]
        public void Test50CompleteCAXYZRecoversTheArcExactly()
        {
            Random random = new Random(20260914);
            List<string> failures = new();
            int arcs = 0;
            double worstAbscissa = 0.0;
            double worstAttitude = 0.0;
            double worstCurvature = 0.0;

            for (int k = 0; k < 2000; k++)
            {
                double inclinationStart = 0.02 + (System.Math.PI - 0.04) * random.NextDouble();
                double azimuthStart = TwoPi * random.NextDouble();
                double curvature = 1e-9 + 0.012 * random.NextDouble();
                double toolface = -System.Math.PI + TwoPi * random.NextDouble();
                double length = 5.0 + 400.0 * random.NextDouble();
                if (curvature * length >= System.Math.PI - 0.02)
                {
                    continue;
                }

                SurveyPoint start = new SurveyPoint()
                {
                    X = 0.0,
                    Y = 0.0,
                    Z = 0.0,
                    Abscissa = 1000.0,
                    Inclination = inclinationStart,
                    Azimuth = azimuthStart
                };
                SurveyPoint forward = new SurveyPoint() { Abscissa = 1000.0 + length };
                if (!start.CompleteCASDT(forward, curvature, toolface) ||
                    forward.X == null || forward.Inclination == null)
                {
                    continue;
                }
                arcs++;

                SurveyPoint recovered = new SurveyPoint() { X = forward.X, Y = forward.Y, Z = forward.Z };
                if (!start.CompleteCAXYZ(recovered) || recovered.Abscissa == null)
                {
                    failures.Add($"arc {k}: no solution was found.");
                    continue;
                }

                worstAbscissa = System.Math.Max(worstAbscissa,
                    System.Math.Abs(recovered.Abscissa.Value - forward.Abscissa!.Value));
                worstAttitude = System.Math.Max(worstAttitude, System.Math.Max(
                    System.Math.Abs(recovered.Inclination!.Value - forward.Inclination.Value),
                    System.Math.Abs(System.Math.IEEERemainder(recovered.Azimuth!.Value - forward.Azimuth!.Value, TwoPi))));
                if (recovered.Curvature != null)
                {
                    worstCurvature = System.Math.Max(worstCurvature,
                        System.Math.Abs(recovered.Curvature.Value - curvature));
                }
            }

            Assert.That(arcs, Is.GreaterThan(1500), "too few usable arcs");
            Assert.That(failures, Is.Empty, string.Join(" | ", failures.Take(8)));
            Assert.That(worstAbscissa, Is.LessThan(1e-9), $"worst abscissa error {worstAbscissa:E3} m");
            Assert.That(worstAttitude, Is.LessThan(1e-9), $"worst attitude error {worstAttitude:E3} rad");
            Assert.That(worstCurvature, Is.LessThan(1e-9), $"worst curvature error {worstCurvature:E3} rad/m");
        }

        /// <summary>
        /// Interpolation along a circular arc: it must carry its own end stations, keep the measured
        /// depth increasing, and report an attitude in the canonical ranges. In particular a vertical
        /// interpolated tangent has no defined azimuth and must inherit the one it started with rather
        /// than produce an arc tangent of zero over zero.
        /// </summary>
        [Test]
        public void Test51InterpolateAtAbscissaCAIsExactAndAlwaysDefined()
        {
            const TrajectoryCalculationType Ca = TrajectoryCalculationType.MinimumCurvatureMethod;
            const int steps = 40;
            Random random = new Random(20260914);
            List<string> failures = new();
            int arcs = 0;

            for (int k = 0; k < 400; k++)
            {
                double inclinationStart = 0.02 + (System.Math.PI - 0.04) * random.NextDouble();
                double azimuthStart = TwoPi * random.NextDouble();
                double curvature = 1e-9 + 0.012 * random.NextDouble();
                double toolface = -System.Math.PI + TwoPi * random.NextDouble();
                double length = 5.0 + 400.0 * random.NextDouble();
                if (curvature * length >= System.Math.PI - 0.02)
                {
                    continue;
                }

                SurveyPoint start = new SurveyPoint()
                {
                    X = 0.0,
                    Y = 0.0,
                    Z = 0.0,
                    Abscissa = 1000.0,
                    Inclination = inclinationStart,
                    Azimuth = azimuthStart
                };
                SurveyPoint next = new SurveyPoint() { Abscissa = 1000.0 + length };
                if (!start.CompleteCASDT(next, curvature, toolface) || next.X == null || next.Inclination == null)
                {
                    continue;
                }
                arcs++;

                SurveyPoint[] points = new SurveyPoint[steps + 1];
                bool complete = true;
                for (int j = 0; j <= steps; j++)
                {
                    double measuredDepth = 1000.0 + length * j / (double)steps;
                    SurveyPoint point = new SurveyPoint();
                    if (!start.InterpolateAtAbscissa(next, measuredDepth, point, Ca) ||
                        point.X == null || point.Inclination == null || point.Azimuth == null ||
                        double.IsNaN(point.X.Value) || double.IsNaN(point.Inclination.Value) ||
                        double.IsNaN(point.Azimuth.Value))
                    {
                        failures.Add($"arc {k}: interpolation failed or was not a number at fraction {j / (double)steps:F3}.");
                        complete = false;
                        break;
                    }
                    points[j] = point;
                }
                if (!complete)
                {
                    continue;
                }

                if (!(System.Math.Abs(points[0].X!.Value - start.X!.Value) <= 1e-12 &&
                      System.Math.Abs(points[steps].X!.Value - next.X.Value) <= 1e-12))
                {
                    failures.Add($"arc {k}: an end station was not reproduced.");
                }
                for (int j = 0; j <= steps; j++)
                {
                    double inclination = points[j].Inclination!.Value;
                    double azimuth = points[j].Azimuth!.Value;
                    if (inclination < -1e-12 || inclination > System.Math.PI + 1e-12 ||
                        azimuth < -1e-12 || azimuth > TwoPi + 1e-9)
                    {
                        failures.Add($"arc {k}: attitude left its canonical range at step {j}.");
                        break;
                    }
                    if (j > 0 && points[j].Abscissa!.Value < points[j - 1].Abscissa!.Value - 1e-12)
                    {
                        failures.Add($"arc {k}: measured depth went backwards at step {j}.");
                        break;
                    }
                }
            }

            Assert.That(arcs, Is.GreaterThan(300), "too few usable arcs");
            Assert.That(failures, Is.Empty, $"{failures.Count} failure(s). " + string.Join(" | ", failures.Take(8)));
        }

        /// <summary>
        /// An arc that runs through vertical leaves the interpolated tangent with no defined azimuth at
        /// the crossing. That case has to be answered, not turned into a value that is not a number.
        /// </summary>
        [Test]
        public void Test52InterpolateAtAbscissaCAHandlesAVerticalTangent()
        {
            const TrajectoryCalculationType Ca = TrajectoryCalculationType.MinimumCurvatureMethod;
            // Dropping straight back to vertical: the end tangent is exactly vertical.
            SurveyPoint start = new SurveyPoint()
            {
                X = 0.0,
                Y = 0.0,
                Z = 0.0,
                Abscissa = 1000.0,
                Inclination = 0.40,
                Azimuth = 1.10
            };
            SurveyPoint next = new SurveyPoint()
            {
                Abscissa = 1200.0,
                Inclination = 0.0,
                Azimuth = 1.10
            };
            Assert.That(start.CompleteCASIA(next), Is.True);

            foreach (double fraction in new[] { 0.25, 0.5, 0.75, 1.0 })
            {
                SurveyPoint point = new SurveyPoint();
                Assert.That(start.InterpolateAtAbscissa(next, 1000.0 + 200.0 * fraction, point, Ca), Is.True,
                    $"interpolation failed at fraction {fraction}");
                Assert.That(point.Inclination, Is.Not.Null);
                Assert.That(point.Azimuth, Is.Not.Null);
                Assert.That(double.IsNaN(point.Inclination!.Value), Is.False,
                    $"inclination was not a number at fraction {fraction}");
                Assert.That(double.IsNaN(point.Azimuth!.Value), Is.False,
                    $"azimuth was not a number at fraction {fraction}");
            }
        }

        /// <summary>
        /// Along a circular arc the toolface angle is not constant, so a single reported value has to be
        /// chosen, and the one chosen is the angle at the start of the arc. That is the angle the arc is
        /// set off at and exactly the argument <see cref="SurveyPoint.CompleteCASDT"/> takes, so the
        /// curvature and toolface angle reported by the survey and target point constructions must feed
        /// straight back into it and reproduce the arc.
        /// </summary>
        [Test]
        public void Test53CircularArcReportsTheToolfaceAtTheStartOfTheArc()
        {
            const TrajectoryCalculationType Ca = TrajectoryCalculationType.MinimumCurvatureMethod;
            Random random = new Random(20260914);
            List<string> failures = new();
            int arcs = 0;
            double worstFromSurvey = 0.0;
            double worstFromTarget = 0.0;
            double worstInterpolated = 0.0;
            double worstRoundTrip = 0.0;

            for (int k = 0; k < 1500; k++)
            {
                double inclinationStart = 0.02 + (System.Math.PI - 0.04) * random.NextDouble();
                double azimuthStart = TwoPi * random.NextDouble();
                double curvature = 1e-6 + 0.012 * random.NextDouble();
                double toolface = -System.Math.PI + TwoPi * random.NextDouble();
                double length = 5.0 + 400.0 * random.NextDouble();
                if (curvature * length >= System.Math.PI - 0.02)
                {
                    continue;
                }

                SurveyPoint start = new SurveyPoint()
                {
                    X = 0.0,
                    Y = 0.0,
                    Z = 0.0,
                    Abscissa = 1000.0,
                    Inclination = inclinationStart,
                    Azimuth = azimuthStart
                };
                SurveyPoint forward = new SurveyPoint() { Abscissa = 1000.0 + length };
                if (!start.CompleteCASDT(forward, curvature, toolface) || forward.Inclination == null)
                {
                    continue;
                }
                arcs++;
                double expected = System.Math.IEEERemainder(toolface, TwoPi);

                double Deviation(double? reported)
                    => reported == null
                        ? double.PositiveInfinity
                        : System.Math.Abs(System.Math.IEEERemainder(reported.Value - expected, TwoPi));

                // From two stations.
                SurveyPoint fromSurvey = new SurveyPoint()
                {
                    Abscissa = forward.Abscissa,
                    Inclination = forward.Inclination,
                    Azimuth = forward.Azimuth
                };
                if (!start.CompleteCASIA(fromSurvey))
                {
                    failures.Add($"arc {k}: the survey construction failed.");
                    continue;
                }
                worstFromSurvey = System.Math.Max(worstFromSurvey, Deviation(fromSurvey.Toolface));

                // From a target coordinate.
                SurveyPoint fromTarget = new SurveyPoint() { X = forward.X, Y = forward.Y, Z = forward.Z };
                if (!start.CompleteCAXYZ(fromTarget))
                {
                    failures.Add($"arc {k}: the target point construction failed.");
                    continue;
                }
                worstFromTarget = System.Math.Max(worstFromTarget, Deviation(fromTarget.Toolface));

                // An interpolated point belongs to the same arc and carries the same pair.
                SurveyPoint interpolated = new SurveyPoint();
                if (!start.InterpolateAtAbscissa(fromSurvey, 1000.0 + 0.37 * length, interpolated, Ca))
                {
                    failures.Add($"arc {k}: interpolation failed.");
                    continue;
                }
                worstInterpolated = System.Math.Max(worstInterpolated, Deviation(interpolated.Toolface));

                // The reported pair must rebuild the arc.
                SurveyPoint rebuilt = new SurveyPoint() { Abscissa = forward.Abscissa };
                if (!start.CompleteCASDT(rebuilt, fromSurvey.Curvature!.Value, fromSurvey.Toolface!.Value) ||
                    rebuilt.X == null)
                {
                    failures.Add($"arc {k}: the reported pair could not be propagated.");
                    continue;
                }
                worstRoundTrip = System.Math.Max(worstRoundTrip, System.Math.Max(
                    System.Math.Abs(rebuilt.X.Value - forward.X!.Value),
                    System.Math.Max(System.Math.Abs(rebuilt.Y!.Value - forward.Y!.Value),
                                    System.Math.Abs(rebuilt.Z!.Value - forward.Z!.Value))));
            }

            Assert.That(arcs, Is.GreaterThan(1000), "too few usable arcs");
            Assert.That(failures, Is.Empty, string.Join(" | ", failures.Take(8)));
            Assert.That(worstFromSurvey, Is.LessThan(1e-9),
                $"the survey construction reported a toolface {worstFromSurvey:E3} rad from the arc's own");
            Assert.That(worstFromTarget, Is.LessThan(1e-9),
                $"the target point construction reported a toolface {worstFromTarget:E3} rad from the arc's own");
            Assert.That(worstInterpolated, Is.LessThan(1e-9),
                $"an interpolated point reported a toolface {worstInterpolated:E3} rad from the arc's own");
            Assert.That(worstRoundTrip, Is.LessThan(1e-8),
                $"rebuilding from the reported pair missed by {worstRoundTrip:E3} m");
        }

        /// <summary>
        /// The toolface angle at the start of a circular arc is a property of the two directions, so
        /// whole turns in either reported azimuth cannot change it.
        /// </summary>
        [Test]
        public void Test54StartToolfaceIsUnaffectedByWholeTurns()
        {
            Random random = new Random(2718);
            for (int k = 0; k < 20000; k++)
            {
                double i1 = 1e-6 + (System.Math.PI - 2e-6) * random.NextDouble();
                double i2 = 1e-6 + (System.Math.PI - 2e-6) * random.NextDouble();
                double a1 = TwoPi * random.NextDouble();
                double a2 = TwoPi * random.NextDouble();

                double direct = SurveyPoint.StartToolface(i1, a1, i2, a2);
                Assert.That(double.IsNaN(direct), Is.False);
                Assert.That(direct, Is.GreaterThan(-System.Math.PI - 1e-12).And.LessThanOrEqualTo(System.Math.PI + 1e-12));

                int turns = random.Next(-3, 4);
                double shifted = SurveyPoint.StartToolface(i1, a1 + TwoPi * turns, i2, a2 + TwoPi * turns);
                Assert.That(System.Math.Abs(System.Math.IEEERemainder(shifted - direct, TwoPi)), Is.LessThan(1e-12),
                    "the start toolface changed when both azimuths were shifted by whole turns");
            }
        }

        /// <summary>
        /// The turn rate between two stations. The azimuth is reported modulo a full turn, so the
        /// difference has to be taken the short way round.
        ///
        /// This previously read "(a2 - a1) % 2.0 * Numeric.PI", which binds as "((a2 - a1) % 2.0) * PI":
        /// the remainder was taken modulo two rather than modulo a full turn, and then multiplied by pi.
        /// An ordinary small turn came back pi times too large.
        /// </summary>
        [TestCase(0.5)]
        [TestCase(1.5)]
        [TestCase(0.1)]
        [TestCase(-0.3)]
        [TestCase(3.0)]
        [TestCase(-2.5)]
        [TestCase(0.001)]
        public void Test55GetTurnRateTakesTheAzimuthTheShortWayRound(double turn)
        {
            const double length = 100.0;
            const double azimuthStart = 1.0;

            // The far azimuth as a survey would report it, folded into a single revolution.
            double reported = (azimuthStart + turn) % TwoPi;
            if (reported < 0.0)
            {
                reported += TwoPi;
            }

            CurvilinearPoint3D start = new CurvilinearPoint3D()
            {
                Abscissa = 1000.0,
                Inclination = 0.7,
                Azimuth = azimuthStart
            };
            CurvilinearPoint3D end = new CurvilinearPoint3D()
            {
                Abscissa = 1000.0 + length,
                Inclination = 0.7,
                Azimuth = reported
            };

            double? rate = start.GetTR(end);
            Assert.That(rate, Is.Not.Null);
            Assert.That(rate!.Value * length, Is.EqualTo(turn).Within(1e-12),
                $"a turn of {turn} rad was reported as {rate.Value * length}");
        }

        /// <summary>
        /// The curve helpers on the curvilinear point and the trajectory constructions must agree,
        /// because they are now one implementation rather than separate copies.
        /// </summary>
        [Test]
        public void Test56CurvilinearPointHelpersShareTheTrajectoryImplementations()
        {
            Random random = new Random(7);
            double worstDogleg = 0.0;
            double worstToolface = 0.0;

            for (int k = 0; k < 20000; k++)
            {
                double inclinationStart = 0.02 + (System.Math.PI - 0.04) * random.NextDouble();
                double azimuthStart = TwoPi * random.NextDouble();
                double inclinationEnd = 0.02 + (System.Math.PI - 0.04) * random.NextDouble();
                double azimuthEnd = TwoPi * random.NextDouble();

                CurvilinearPoint3D start = new CurvilinearPoint3D()
                {
                    Abscissa = 1000.0,
                    Inclination = inclinationStart,
                    Azimuth = azimuthStart
                };
                CurvilinearPoint3D end = new CurvilinearPoint3D()
                {
                    Abscissa = 1100.0,
                    Inclination = inclinationEnd,
                    Azimuth = azimuthEnd
                };

                worstDogleg = System.Math.Max(worstDogleg, System.Math.Abs(
                    start.GetDLS(end)!.Value * 100.0
                    - CurvilinearPoint3D.DoglegAngle(inclinationStart, azimuthStart, inclinationEnd, azimuthEnd)));
                worstToolface = System.Math.Max(worstToolface, System.Math.Abs(
                    start.GetToolface(end)!.Value
                    - CurvilinearPoint3D.StartToolface(inclinationStart, azimuthStart, inclinationEnd, azimuthEnd)));
            }

            Assert.That(worstDogleg, Is.LessThan(1e-12), $"GetDLS drifted from DoglegAngle by {worstDogleg:E3}");
            Assert.That(worstToolface, Is.LessThan(1e-12), $"GetToolface drifted from StartToolface by {worstToolface:E3}");
        }

        /// <summary>
        /// The minimum curvature construction must stay accurate on a nearly straight segment, which the
        /// arc cosine form of the dogleg angle did not.
        /// </summary>
        [TestCase(1e-3)]
        [TestCase(1e-7)]
        [TestCase(1e-9)]
        [TestCase(1e-11)]
        public void Test57MinimumCurvatureIsAccurateWhenNearlyStraight(double dogleg)
        {
            const double length = 100.0;
            CurvilinearPoint3D start = new CurvilinearPoint3D()
            {
                X = 0.0,
                Y = 0.0,
                Z = 0.0,
                Abscissa = 1000.0,
                Inclination = 0.7,
                Azimuth = 1.3
            };
            CurvilinearPoint3D end = new CurvilinearPoint3D()
            {
                Abscissa = 1000.0 + length,
                Inclination = 0.7 + dogleg,
                Azimuth = 1.3
            };
            start.MinimumCurvatureMethod(end);

            // Over a nearly straight segment the chord must fall short of the length by no more than the
            // sagitta, which is of order length * dogleg^2 / 24.
            double chord = System.Math.Sqrt(Sq(end.X!.Value) + Sq(end.Y!.Value) + Sq(end.Z!.Value));
            double allowed = length * dogleg * dogleg / 24.0 + 1e-9;
            Assert.That(length - chord, Is.GreaterThanOrEqualTo(-1e-9).And.LessThanOrEqualTo(allowed),
                $"chord {chord:F12} against a length of {length} at a dogleg of {dogleg:E1}");
        }

        // ------------------------------------------------------------------
        // JSON shapes
        // ------------------------------------------------------------------

        private class VectorFile
        {
            [JsonPropertyName("inverse_cases")] public List<InverseCase>? InverseCases { get; set; }
            [JsonPropertyName("forward_cases")] public List<ForwardCase>? ForwardCases { get; set; }
        }

        private class InverseCase
        {
            [JsonPropertyName("name")] public string? Name { get; set; }
            [JsonPropertyName("input")] public CaseInput? Input { get; set; }
            [JsonPropertyName("expected")] public InverseExpected? Expected { get; set; }
        }

        private class CaseInput
        {
            [JsonPropertyName("theta0")] public double Theta0 { get; set; }
            [JsonPropertyName("alpha0")] public double Alpha0 { get; set; }
            [JsonPropertyName("theta1")] public double Theta1 { get; set; }
            [JsonPropertyName("alpha1")] public double Alpha1 { get; set; }
            [JsonPropertyName("dMD")] public double DMD { get; set; }
            [JsonPropertyName("branch")] public int Branch { get; set; }
            [JsonPropertyName("N0")] public double N0 { get; set; }
            [JsonPropertyName("E0")] public double E0 { get; set; }
            [JsonPropertyName("V0")] public double V0 { get; set; }
        }

        private class InverseExpected
        {
            [JsonPropertyName("kappa")] public double Kappa { get; set; }
            [JsonPropertyName("phi")] public double Phi { get; set; }
            [JsonPropertyName("beta")] public double Beta { get; set; }
            [JsonPropertyName("t")] public double T { get; set; }
            [JsonPropertyName("G")] public double G { get; set; }
            [JsonPropertyName("dalpha")] public double DAlpha { get; set; }
            [JsonPropertyName("tau0")] public double Tau0 { get; set; }
            [JsonPropertyName("tau1")] public double Tau1 { get; set; }
            [JsonPropertyName("dogleg")] public double Dogleg { get; set; }
            [JsonPropertyName("N1")] public double N1 { get; set; }
            [JsonPropertyName("E1")] public double E1 { get; set; }
            [JsonPropertyName("V1")] public double V1 { get; set; }
            [JsonPropertyName("A")] public double A { get; set; }
            [JsonPropertyName("interior")] public List<InteriorPoint>? Interior { get; set; }
        }

        private class InteriorPoint
        {
            [JsonPropertyName("fraction")] public double Fraction { get; set; }
            [JsonPropertyName("s")] public double S { get; set; }
            [JsonPropertyName("theta")] public double Theta { get; set; }
            [JsonPropertyName("alpha")] public double Alpha { get; set; }
        }

        private class ForwardCase
        {
            [JsonPropertyName("name")] public string? Name { get; set; }
            [JsonPropertyName("input")] public ForwardInput? Input { get; set; }
            [JsonPropertyName("expected")] public ForwardExpected? Expected { get; set; }
        }

        private class ForwardInput
        {
            [JsonPropertyName("theta0")] public double Theta0 { get; set; }
            [JsonPropertyName("alpha0")] public double Alpha0 { get; set; }
            [JsonPropertyName("kappa")] public double Kappa { get; set; }
            [JsonPropertyName("phi")] public double Phi { get; set; }
            [JsonPropertyName("L")] public double L { get; set; }
            [JsonPropertyName("N0")] public double N0 { get; set; }
            [JsonPropertyName("E0")] public double E0 { get; set; }
            [JsonPropertyName("V0")] public double V0 { get; set; }
        }

        private class ForwardExpected
        {
            [JsonPropertyName("theta1")] public double Theta1 { get; set; }
            [JsonPropertyName("alpha1")] public double Alpha1 { get; set; }
            [JsonPropertyName("N1")] public double N1 { get; set; }
            [JsonPropertyName("E1")] public double E1 { get; set; }
            [JsonPropertyName("V1")] public double V1 { get; set; }
        }
    }
}
