using OSDC.DotnetLibraries.General.Math;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace OSDC.DotnetLibraries.Drilling.Surveying.UnitTest
{
    /// <summary>
    /// Golden vector tests for <see cref="ReducedOrderTrajectory"/>.
    ///
    /// The vectors in reduced_order_trajectory_vectors.json were generated by the Python reference
    /// implementation of the reduced order trajectory method, in float64 and in SI units, in the frame
    /// north, east and vertical downward. Each group carries its own declared tolerance, given in section
    /// 12 of the specification and repeated on each test below.
    ///
    /// The tests are grouped by the stage of the method they cover, so that a failure says at once which
    /// layer is wrong: the geometric primitives, the closed form fits and the segmentation built on them,
    /// or the refinement on top of that.
    /// </summary>
    public class ReducedOrderTrajectoryVectorTests
    {
        private static VectorFile LoadVectors()
        {
            string path = Path.Combine(TestContext.CurrentContext.TestDirectory, "reduced_order_trajectory_vectors.json");
            Assert.That(File.Exists(path), Is.True, $"Reference vector file not found at {path}.");
            VectorFile? file = JsonSerializer.Deserialize<VectorFile>(File.ReadAllText(path));
            Assert.That(file, Is.Not.Null);
            return file!;
        }

        private static void AssertAbsolute(double actual, double expected, double tolerance, string what, List<string> failures)
        {
            double error = System.Math.Abs(actual - expected);
            if (!(error <= tolerance))
            {
                failures.Add($"{what}: expected {expected:R}, got {actual:R}, absolute error {error:E3}");
            }
        }

        private static void AssertTangent(double[] tangents, int index, IReadOnlyList<double> expected, double tolerance, string what, List<string> failures)
        {
            AssertAbsolute(tangents[3 * index], expected[0], tolerance, what + " north", failures);
            AssertAbsolute(tangents[3 * index + 1], expected[1], tolerance, what + " east", failures);
            AssertAbsolute(tangents[3 * index + 2], expected[2], tolerance, what + " vertical", failures);
        }

        /// <summary>
        /// The numeric values of <see cref="ReducedOrderCurveType"/> are part of the interchange format
        /// and of every vector carrying a curve type, so they are pinned here rather than left to the
        /// order the members happen to be declared in.
        /// </summary>
        [Test]
        public void Test58ReducedOrderCurveTypeValuesMatchTheReferenceVectors()
        {
            VectorFile file = LoadVectors();
            CurveTypeMap map = file.CurveTypes!;
            Assert.Multiple(() =>
            {
                Assert.That(map.Hold, Is.EqualTo((int)ReducedOrderCurveType.Hold));
                Assert.That(map.CircularArc, Is.EqualTo((int)ReducedOrderCurveType.CircularArc));
                Assert.That(map.ConstantToolface, Is.EqualTo((int)ReducedOrderCurveType.ConstantCurvatureAndToolface));
                Assert.That(map.ConstantBuildTurn, Is.EqualTo((int)ReducedOrderCurveType.ConstantBuildAndTurn));
            });
            Assert.That(ReducedOrderTrajectory.DefaultMinimumSineInclination,
                Is.EqualTo(file.MinSinTheta).Within(1.0e-11),
                "The default vertical guard must be the sine of three degrees, as the vectors were generated with.");
        }

        /// <summary>
        /// The unit tangent from an inclination and an azimuth. Specification section 0, tolerance 1e-12.
        /// </summary>
        [Test]
        public void Test59TangentFromAnglesMatchesReferenceVectors()
        {
            VectorFile file = LoadVectors();
            List<string> failures = new();
            for (int c = 0; c < file.TangentFromAngles!.Count; c++)
            {
                TangentCase one = file.TangentFromAngles[c];
                ReducedOrderTrajectory.TangentFromAngles(one.Inclination, one.Azimuth,
                    out double north, out double east, out double vertical);
                string what = $"case {c} (inclination {one.Inclination:R}, azimuth {one.Azimuth:R})";
                AssertAbsolute(north, one.Tangent![0], 1.0e-12, what + " north", failures);
                AssertAbsolute(east, one.Tangent[1], 1.0e-12, what + " east", failures);
                AssertAbsolute(vertical, one.Tangent[2], 1.0e-12, what + " vertical", failures);
            }
            Assert.That(failures, Is.Empty, string.Join(System.Environment.NewLine, failures));
        }

        /// <summary>
        /// The perpendicular frame a circular arc's two parameters are resolved onto. Specification
        /// section 3.0, tolerance 1e-12.
        /// </summary>
        [Test]
        public void Test60PerpendicularBasisMatchesReferenceVectors()
        {
            VectorFile file = LoadVectors();
            List<string> failures = new();
            for (int c = 0; c < file.OrthoBasis!.Count; c++)
            {
                BasisCase one = file.OrthoBasis[c];
                ReducedOrderTrajectory.PerpendicularBasis(one.T0![0], one.T0[1], one.T0[2],
                    out double e1North, out double e1East, out double e1Vertical,
                    out double e2North, out double e2East, out double e2Vertical);
                string what = $"case {c}";
                AssertAbsolute(e1North, one.E1![0], 1.0e-12, what + " e1 north", failures);
                AssertAbsolute(e1East, one.E1[1], 1.0e-12, what + " e1 east", failures);
                AssertAbsolute(e1Vertical, one.E1[2], 1.0e-12, what + " e1 vertical", failures);
                AssertAbsolute(e2North, one.E2![0], 1.0e-12, what + " e2 north", failures);
                AssertAbsolute(e2East, one.E2[1], 1.0e-12, what + " e2 east", failures);
                AssertAbsolute(e2Vertical, one.E2[2], 1.0e-12, what + " e2 vertical", failures);
            }
            Assert.That(failures, Is.Empty, string.Join(System.Environment.NewLine, failures));
        }

        /// <summary>
        /// Positions by the minimum curvature method. Specification section 2.1, tolerance 1e-9 m.
        /// </summary>
        [Test]
        public void Test61MinimumCurvatureMatchesReferenceVectors()
        {
            VectorFile file = LoadVectors();
            MinimumCurvatureCase one = file.MinimumCurvature!;
            List<string> failures = new();

            double[] measuredDepths = one.Md!.ToArray();
            int count = measuredDepths.Length;
            double[] tangents = new double[3 * count];
            ReducedOrderTrajectory.TangentsFromAngles(one.Inclination!.ToArray(), one.Azimuth!.ToArray(), tangents);

            // The tangents the reference computed from the same angles, checked first so that a failure
            // downstream cannot be blamed on them.
            for (int i = 0; i < count; i++)
            {
                AssertTangent(tangents, i, one.Tangents![i], 1.0e-12, $"tangent {i}", failures);
            }

            double[] positions = new double[3 * count];
            ReducedOrderTrajectory.MinimumCurvature(measuredDepths, tangents, positions);
            for (int i = 0; i < count; i++)
            {
                AssertTangent(positions, i, one.Positions![i], 1.0e-9, $"position {i}", failures);
            }
            Assert.That(failures, Is.Empty, string.Join(System.Environment.NewLine, failures));
        }

        /// <summary>
        /// The forward evaluation of all four curve families, including the degenerate cases the method
        /// has to pass through smoothly: zero curvature on an arc, zero build up rate on a constant
        /// curvature and toolface curve, and a section starting from the vertical. Specification sections
        /// 3.1 to 3.4, tolerance 1e-10.
        /// </summary>
        [Test]
        public void Test62SectionTangentsMatchReferenceVectors()
        {
            VectorFile file = LoadVectors();
            List<string> failures = new();
            for (int c = 0; c < file.SectionTangents!.Count; c++)
            {
                SectionCase one = file.SectionTangents[c];
                double[] distances = one.U!.ToArray();
                double[] tangents = new double[3 * distances.Length];
                ReducedOrderTrajectory.SectionTangents(
                    (ReducedOrderCurveType)one.CurveType, one.P1, one.P2,
                    one.T0![0], one.T0[1], one.T0[2],
                    distances, 0, distances.Length, tangents, 0);
                string what = $"case {c} ({one.CurveTypeName} from {one.T0Name}, p1 {one.P1:R}, p2 {one.P2:R})";
                for (int i = 0; i < distances.Length; i++)
                {
                    AssertTangent(tangents, i, one.Tangents![i], 1.0e-10, $"{what} at u {distances[i]:R}", failures);
                }
            }
            Assert.That(failures, Is.Empty, string.Join(System.Environment.NewLine, failures));
        }

        /// <summary>
        /// The Rodrigues rotation carrying one direction onto another, which the chained initialisation
        /// uses to re fit a section in the frame it actually inherits. Specification section 7.1,
        /// tolerance 1e-12.
        /// </summary>
        [Test]
        public void Test63RotationAligningMatchesReferenceVectors()
        {
            VectorFile file = LoadVectors();
            List<string> failures = new();
            double[] rotation = new double[9];
            for (int c = 0; c < file.RotAlign!.Count; c++)
            {
                RotationCase one = file.RotAlign[c];
                ReducedOrderTrajectory.RotationAligning(
                    one.A![0], one.A[1], one.A[2],
                    one.B![0], one.B[1], one.B[2],
                    rotation);
                string what = $"case {c}";
                for (int row = 0; row < 3; row++)
                {
                    for (int column = 0; column < 3; column++)
                    {
                        AssertAbsolute(rotation[3 * row + column], one.R![row][column], 1.0e-12,
                            $"{what} R[{row},{column}]", failures);
                    }
                }
                ReducedOrderTrajectory.ApplyRotation(rotation, one.A[0], one.A[1], one.A[2],
                    out double north, out double east, out double vertical);
                AssertAbsolute(north, one.Ra![0], 1.0e-12, what + " R a north", failures);
                AssertAbsolute(east, one.Ra[1], 1.0e-12, what + " R a east", failures);
                AssertAbsolute(vertical, one.Ra[2], 1.0e-12, what + " R a vertical", failures);
            }
            Assert.That(failures, Is.Empty, string.Join(System.Environment.NewLine, failures));
        }

        /// <summary>
        /// The closed form parameters and the L infinity angular residual of all four families, on 36
        /// intervals taken from three real wells. Specification section 5, tolerance 1e-9 on both the
        /// parameters and the residual.
        /// </summary>
        [Test]
        public void Test64ClosedFormFitsMatchReferenceVectors()
        {
            VectorFile file = LoadVectors();
            Dictionary<string, WellArrays> wells = LoadWells(file);
            List<string> failures = new();

            foreach (FitCase one in file.ClosedFormFits!)
            {
                WellArrays well = wells[one.Well!];
                double residual = ReducedOrderTrajectory.FitSection(
                    (ReducedOrderCurveType)one.CurveType,
                    well.MeasuredDepths, well.Tangents, well.Inclinations, well.Azimuths,
                    one.I, one.J,
                    out double firstParameter, out double secondParameter);
                string what = $"{one.Well} [{one.I},{one.J}] as {(ReducedOrderCurveType)one.CurveType}";
                AssertAbsolute(firstParameter, one.P1, 1.0e-9, what + " first parameter", failures);
                AssertAbsolute(secondParameter, one.P2, 1.0e-9, what + " second parameter", failures);
                // The residual is an arc cosine of a dot product of two nearly parallel directions, where
                // the arc cosine multiplies any error in its argument by one over the sine of the angle it
                // returns. The declared tolerance of 1e-9 is therefore applied to the dot product, which is
                // the well conditioned quantity, and carried through to the angle. On these intervals that
                // comes to a few times 1e-8; a porting error would be larger by five orders of magnitude.
                double residualTolerance = 1.0e-9 / System.Math.Max(System.Math.Sin(one.MaxAngularResidual), 1.0e-6);
                AssertAbsolute(residual, one.MaxAngularResidual, residualTolerance, what + " residual", failures);
            }
            Assert.That(failures, Is.Empty, string.Join(System.Environment.NewLine, failures));
        }

        /// <summary>
        /// The greedy segmentation, on three wells at three tolerances. Specification section 6. The
        /// breakpoints and the curve types have to match exactly: the search is deterministic, so any
        /// difference means the order the families are tried in, or the rule that breaks a tie between
        /// two families reaching equally far, is wrong.
        ///
        /// This runs with <see cref="ReductionOptions.ReproduceReferenceSegmentation"/> set, because the
        /// vectors record what the reference does and the reference cuts the last section of a well short.
        /// See <see cref="Test80GallopingLeavesTheLastStationUntestedWhenItOvershoots"/>.
        /// </summary>
        [Test]
        public void Test65SegmentationMatchesReferenceVectorsExactly()
        {
            VectorFile file = LoadVectors();
            Dictionary<string, WellArrays> wells = LoadWells(file);
            List<string> failures = new();

            foreach (SegmentationCase one in file.Segmentation!)
            {
                WellArrays well = wells[one.Well!];
                double tolerance = one.ToleranceDeg * System.Math.PI / 180.0;
                ReducedOrderTrajectory.Segment(
                    well.MeasuredDepths, well.Tangents, well.Inclinations, well.Azimuths,
                    tolerance, file.MinSinTheta, true,
                    out int[] breaks, out ReducedOrderCurveType[] types);
                string what = $"{one.Well} at {one.ToleranceDeg} deg";

                if (types.Length != one.SectionCount)
                {
                    failures.Add($"{what}: expected {one.SectionCount} sections, got {types.Length}");
                    continue;
                }
                if (breaks.Length != one.Breaks!.Count)
                {
                    failures.Add($"{what}: expected {one.Breaks.Count} breakpoints, got {breaks.Length}");
                    continue;
                }
                for (int q = 0; q < breaks.Length; q++)
                {
                    if (breaks[q] != one.Breaks[q])
                    {
                        failures.Add($"{what}: breakpoint {q} expected {one.Breaks[q]}, got {breaks[q]}");
                    }
                }
                for (int q = 0; q < types.Length; q++)
                {
                    if ((int)types[q] != one.Types![q])
                    {
                        failures.Add($"{what}: section {q} expected {(ReducedOrderCurveType)one.Types[q]}, got {types[q]}");
                    }
                }
            }
            Assert.That(failures, Is.Empty, string.Join(System.Environment.NewLine, failures));
        }

        /// <summary>
        /// The parameters witnessing that a family fits an interval also satisfy every part of that
        /// interval, which is the hereditary property the greedy search rests on. Specification section 6.
        ///
        /// Note carefully what this does and does not say. It is about the <i>same</i> parameters carried
        /// onto a shorter interval, which is what <see cref="ReducedOrderTrajectory.SectionResidual"/>
        /// measures. It is not about re-fitting the shorter interval in its own right: the closed form
        /// fits are least squares regressions rather than minimax fits, so a shorter interval re-fitted
        /// can report a <i>larger</i> residual than the longer one it sits inside, and the feasibility
        /// test the segmentation actually applies is therefore not monotone in the interval end. The
        /// galloping search reproduces the reference exactly, breakpoint for breakpoint, but it is a
        /// heuristic rather than the provably optimal search the specification describes.
        /// </summary>
        [Test]
        public void Test66FittedParametersSatisfyEverySubInterval()
        {
            VectorFile file = LoadVectors();
            Dictionary<string, WellArrays> wells = LoadWells(file);
            WellArrays well = wells["2_8-N-16 T2"];
            List<string> failures = new();

            for (int family = 0; family < 4; family++)
            {
                ReducedOrderCurveType curveType = (ReducedOrderCurveType)family;
                for (int first = 0; first + 40 < well.MeasuredDepths.Length; first += 37)
                {
                    int last = first + 40;
                    double whole = ReducedOrderTrajectory.FitSection(curveType,
                        well.MeasuredDepths, well.Tangents, well.Inclinations, well.Azimuths,
                        first, last, out double p1, out double p2);
                    for (int inner = first + 1; inner < last; inner++)
                    {
                        double part = ReducedOrderTrajectory.SectionResidual(curveType, p1, p2,
                            well.MeasuredDepths, well.Tangents, first, inner);
                        if (part > whole + 1.0e-12)
                        {
                            failures.Add($"{curveType} [{first},{last}] residual {whole:E3} but the same "
                                + $"parameters on [{first},{inner}] give {part:E3}");
                        }
                    }
                }
            }
            Assert.That(failures, Is.Empty, string.Join(System.Environment.NewLine, failures));
        }

        /// <summary>
        /// The counterpart of the note on <see cref="Test66FittedParametersSatisfyEverySubInterval"/>,
        /// recorded as a test so that the limitation is visible rather than folklore: re-fitting a shorter
        /// interval can give a worse residual than the longer interval containing it, so feasibility as
        /// the segmentation tests it is not monotone. If this ever stops holding, the closed form fits
        /// have become minimax fits and the greedy search has become provably optimal, which would be
        /// worth knowing.
        /// </summary>
        [Test]
        public void Test67RefittedFeasibilityIsNotMonotone()
        {
            VectorFile file = LoadVectors();
            Dictionary<string, WellArrays> wells = LoadWells(file);
            WellArrays well = wells["2_8-N-16 T2"];

            double whole = ReducedOrderTrajectory.FitSection(ReducedOrderCurveType.ConstantCurvatureAndToolface,
                well.MeasuredDepths, well.Tangents, well.Inclinations, well.Azimuths, 444, 484, out _, out _);
            double part = ReducedOrderTrajectory.FitSection(ReducedOrderCurveType.ConstantCurvatureAndToolface,
                well.MeasuredDepths, well.Tangents, well.Inclinations, well.Azimuths, 444, 466, out _, out _);
            Assert.That(part, Is.GreaterThan(whole),
                "The shorter interval, re-fitted in its own right, is expected to be the worse of the two "
                + "here. Re-fitting is a least squares regression, not a minimax fit.");
        }

        /// <summary>
        /// The two azimuth carrying families are kept out of any interval reaching a station too close to
        /// the vertical, where the azimuth stops meaning anything. Specification section 3.5. The third
        /// well of the set is vertical from end to end, so nothing but a hold or an arc may appear in it.
        /// </summary>
        [Test]
        public void Test68VerticalSectionsCarryNoAzimuthBasedCurve()
        {
            VectorFile file = LoadVectors();
            Dictionary<string, WellArrays> wells = LoadWells(file);
            List<string> failures = new();

            foreach (SegmentationCase one in file.Segmentation!)
            {
                WellArrays well = wells[one.Well!];
                double tolerance = one.ToleranceDeg * System.Math.PI / 180.0;
                ReducedOrderTrajectory.Segment(
                    well.MeasuredDepths, well.Tangents, well.Inclinations, well.Azimuths,
                    tolerance, file.MinSinTheta, true,
                    out int[] breaks, out ReducedOrderCurveType[] types);

                for (int q = 0; q < types.Length; q++)
                {
                    if (types[q] != ReducedOrderCurveType.ConstantCurvatureAndToolface
                        && types[q] != ReducedOrderCurveType.ConstantBuildAndTurn)
                    {
                        continue;
                    }
                    for (int n = breaks[q]; n <= breaks[q + 1]; n++)
                    {
                        if (System.Math.Sin(well.Inclinations[n]) < file.MinSinTheta)
                        {
                            failures.Add($"{one.Well} at {one.ToleranceDeg} deg: section {q} is {types[q]} "
                                + $"but station {n} has sin(inclination) "
                                + $"{System.Math.Sin(well.Inclinations[n]):E3}");
                            break;
                        }
                    }
                }
            }
            Assert.That(failures, Is.Empty, string.Join(System.Environment.NewLine, failures));
        }

        /// <summary>
        /// Segmentation is deterministic: the same input has to give the same cut every time, with no
        /// dependence on the order anything happens to be enumerated in.
        /// </summary>
        [Test]
        public void Test69SegmentationIsReproducible()
        {
            VectorFile file = LoadVectors();
            Dictionary<string, WellArrays> wells = LoadWells(file);
            WellArrays well = wells["2_11-A-1 A"];
            double tolerance = 1.3 * System.Math.PI / 180.0;

            ReducedOrderTrajectory.Segment(well.MeasuredDepths, well.Tangents, well.Inclinations,
                well.Azimuths, tolerance, file.MinSinTheta, out int[] first, out ReducedOrderCurveType[] firstTypes);
            for (int repeat = 0; repeat < 3; repeat++)
            {
                ReducedOrderTrajectory.Segment(well.MeasuredDepths, well.Tangents, well.Inclinations,
                    well.Azimuths, tolerance, file.MinSinTheta, out int[] again, out ReducedOrderCurveType[] againTypes);
                Assert.That(again, Is.EqualTo(first), $"breakpoints differ on run {repeat + 1}");
                Assert.That(againTypes, Is.EqualTo(firstTypes), $"curve types differ on run {repeat + 1}");
            }
        }

        /// <summary>
        /// The whole method through its public entry point, on six cases across three wells.
        /// Specification section 12.
        ///
        /// The segmentation has to match exactly, as in
        /// <see cref="Test65SegmentationMatchesReferenceVectorsExactly"/>; it is checked here through the
        /// measured depths the sections run between rather than through station indices, since that is
        /// what a caller sees. The refined parameters do not have to match: a different Levenberg
        /// Marquardt lands on a different point of the same basin, so the criterion is on what the answer
        /// achieves. A reduction is accepted when its largest deviation is within a quarter of the
        /// reference's, or within five centimetres of it, whichever is the more forgiving, and when the
        /// positions it reports at the sampled stations are within that same bound of the original survey.
        ///
        /// This runs with <see cref="ReductionOptions.ReproduceReferenceSegmentation"/> set, so that it
        /// is comparing like with like: the reference deviations belong to the reference's own cut.
        /// <see cref="Test81CorrectedSegmentationCostsNoAccuracy"/> covers the cut a caller gets.
        /// </summary>
        [Test]
        public void Test70EndToEndReachesTheReferenceAccuracy()
        {
            VectorFile file = LoadVectors();
            Dictionary<string, WellArrays> wells = LoadWells(file);
            List<string> failures = new();

            foreach (EndToEndCase one in file.EndToEnd!)
            {
                WellArrays well = wells[one.Well!];
                string what = $"{one.Well} at {one.ToleranceDeg} deg";
                ReducedOrderTrajectory reduced = ReducedOrderTrajectory.Reduce(
                    well.MeasuredDepths, well.Inclinations, well.Azimuths,
                    one.ToleranceDeg * System.Math.PI / 180.0,
                    new ReductionOptions() { ReproduceReferenceSegmentation = true });
                Assert.That(reduced.IsValid, Is.True, $"{what}: {reduced.FailureDescription}");

                if (reduced.SectionCount != one.SectionCount)
                {
                    failures.Add($"{what}: expected {one.SectionCount} sections, got {reduced.SectionCount}");
                    continue;
                }
                for (int q = 0; q < reduced.SectionCount; q++)
                {
                    ReducedOrderSection section = reduced.Sections[q];
                    if ((int)section.CurveType != one.Types![q])
                    {
                        failures.Add($"{what}: section {q} expected {(ReducedOrderCurveType)one.Types[q]}, "
                            + $"got {section.CurveType}");
                    }
                    double expectedStart = well.MeasuredDepths[one.Breaks![q]];
                    double expectedEnd = well.MeasuredDepths[one.Breaks[q + 1]];
                    AssertAbsolute(section.StartMeasuredDepth, expectedStart, 1.0e-9,
                        $"{what}: section {q} start", failures);
                    AssertAbsolute(section.EndMeasuredDepth, expectedEnd, 1.0e-9,
                        $"{what}: section {q} end", failures);
                }

                double allowed = System.Math.Max(1.25 * one.ReferenceMaxDeviation,
                    one.ReferenceMaxDeviation + 0.05);
                if (!(reduced.MaxDeviation <= allowed))
                {
                    failures.Add($"{what}: max deviation {reduced.MaxDeviation:F4} m exceeds the allowed "
                        + $"{allowed:F4} m (reference {one.ReferenceMaxDeviation:F4} m)");
                }

                for (int s = 0; s < one.SampleStationIndices!.Count; s++)
                {
                    int station = one.SampleStationIndices[s];
                    Point3D? position = reduced.PositionAt(well.MeasuredDepths[station]);
                    Assert.That(position, Is.Not.Null, $"{what}: no position at station {station}");
                    IReadOnlyList<double> original = one.OriginalPositionsAtSamples![s];
                    double north = (position!.X ?? 0.0) - original[0];
                    double east = (position.Y ?? 0.0) - original[1];
                    double vertical = (position.Z ?? 0.0) - original[2];
                    double distance = System.Math.Sqrt(north * north + east * east + vertical * vertical);
                    if (!(distance <= allowed))
                    {
                        failures.Add($"{what}: station {station} is {distance:F4} m from the original, "
                            + $"allowed {allowed:F4} m");
                    }
                }

                TestContext.Out.WriteLine(
                    $"{what}: {reduced.SectionCount} sections "
                    + $"({reduced.CountOf(ReducedOrderCurveType.Hold)} hold, "
                    + $"{reduced.CountOf(ReducedOrderCurveType.CircularArc)} arc, "
                    + $"{reduced.CountOf(ReducedOrderCurveType.ConstantCurvatureAndToolface)} ctc, "
                    + $"{reduced.CountOf(ReducedOrderCurveType.ConstantBuildAndTurn)} cbt), "
                    + $"max {reduced.MaxDeviation:F4} m (reference {one.ReferenceMaxDeviation:F4}), "
                    + $"rms {reduced.RmsDeviation:F4} m (reference {one.ReferenceRmsDeviation:F4})");
            }
            Assert.That(failures, Is.Empty, string.Join(System.Environment.NewLine, failures));
        }

        /// <summary>
        /// The refinement dominates the cost of a reduction, and a planning tool calls it interactively.
        /// The bound asserted here is far above what the method takes, so that the test says something has
        /// gone badly wrong rather than that the machine was busy. Note that a test run is a debug build,
        /// where this is some three times slower than the release build a caller would use.
        /// </summary>
        [Test]
        public void Test71ReductionOfALongWellIsFastEnough()
        {
            VectorFile file = LoadVectors();
            Dictionary<string, WellArrays> wells = LoadWells(file);
            WellArrays well = wells["2_8-N-16 T2"];
            double tolerance = 3.0 * System.Math.PI / 180.0;

            // Once first, so that the measurement is not paying for the jitting of everything below it.
            ReducedOrderTrajectory.Reduce(well.MeasuredDepths, well.Inclinations, well.Azimuths, tolerance);

            System.Diagnostics.Stopwatch clock = System.Diagnostics.Stopwatch.StartNew();
            ReducedOrderTrajectory reduced = ReducedOrderTrajectory.Reduce(
                well.MeasuredDepths, well.Inclinations, well.Azimuths, tolerance);
            clock.Stop();

            TestContext.Out.WriteLine($"{well.MeasuredDepths.Length} stations reduced to "
                + $"{reduced.SectionCount} sections in {clock.ElapsedMilliseconds} ms, "
                + $"max deviation {reduced.MaxDeviation:F4} m");
            Assert.That(clock.Elapsed.TotalSeconds, Is.LessThan(2.0),
                "A five hundred station well at three degrees should reduce in well under a second.");
        }

        /// <summary>
        /// The same input and the same seed give the same answer, including through the random restarts
        /// of the refinement.
        /// </summary>
        [Test]
        public void Test72ReductionIsReproducible()
        {
            VectorFile file = LoadVectors();
            Dictionary<string, WellArrays> wells = LoadWells(file);
            WellArrays well = wells["2_11-A-1 A"];
            double tolerance = 1.3 * System.Math.PI / 180.0;

            ReducedOrderTrajectory first = ReducedOrderTrajectory.Reduce(
                well.MeasuredDepths, well.Inclinations, well.Azimuths, tolerance);
            for (int repeat = 0; repeat < 2; repeat++)
            {
                ReducedOrderTrajectory again = ReducedOrderTrajectory.Reduce(
                    well.MeasuredDepths, well.Inclinations, well.Azimuths, tolerance);
                Assert.That(again.SectionCount, Is.EqualTo(first.SectionCount));
                Assert.That(again.MaxDeviation, Is.EqualTo(first.MaxDeviation));
                Assert.That(again.InitialInclination, Is.EqualTo(first.InitialInclination));
                Assert.That(again.InitialAzimuth, Is.EqualTo(first.InitialAzimuth));
                for (int q = 0; q < first.SectionCount; q++)
                {
                    Assert.That(again.Sections[q].FirstParameter,
                        Is.EqualTo(first.Sections[q].FirstParameter), $"section {q} on run {repeat + 1}");
                    Assert.That(again.Sections[q].SecondParameter,
                        Is.EqualTo(first.Sections[q].SecondParameter), $"section {q} on run {repeat + 1}");
                }
            }
        }

        /// <summary>
        /// The refinement is never allowed to return something worse than the chained initialisation it
        /// started from, because the starting point stays a candidate throughout. Specification section
        /// 8.2. This also shows what the refinement is worth: without it the chained profile drifts badly.
        /// </summary>
        [Test]
        public void Test73RefinementNeverLosesToItsStartingPoint()
        {
            VectorFile file = LoadVectors();
            Dictionary<string, WellArrays> wells = LoadWells(file);
            List<string> lines = new();

            foreach (string name in new[] { "2_8-N-16 T2", "2_11-A-1 A" })
            {
                WellArrays well = wells[name];
                double tolerance = 1.3 * System.Math.PI / 180.0;
                ReducedOrderTrajectory refined = ReducedOrderTrajectory.Reduce(
                    well.MeasuredDepths, well.Inclinations, well.Azimuths, tolerance);
                ReducedOrderTrajectory chained = ReducedOrderTrajectory.Reduce(
                    well.MeasuredDepths, well.Inclinations, well.Azimuths, tolerance,
                    new ReductionOptions() { Refine = false });
                lines.Add($"{name}: chained {chained.MaxDeviation:F3} m, refined {refined.MaxDeviation:F3} m");
                Assert.That(refined.MaxDeviation, Is.LessThanOrEqualTo(chained.MaxDeviation + 1.0e-9),
                    $"{name}: the refinement returned a worse answer than its starting point.");
            }
            TestContext.Out.WriteLine(string.Join(System.Environment.NewLine, lines));
        }

        /// <summary>
        /// Reduction to a stated distance. Specification section 10. The answer has to meet the distance
        /// asked for, and it has to be the coarsest rung of the ladder that does, which is the one with
        /// the fewest sections.
        /// </summary>
        [Test]
        public void Test74ReduceToDeviationTakesTheCoarsestRungThatWillDo()
        {
            VectorFile file = LoadVectors();
            Dictionary<string, WellArrays> wells = LoadWells(file);
            List<string> lines = new();

            foreach (string name in new[] { "2_8-N-16 T2", "2_11-A-1 A" })
            {
                WellArrays well = wells[name];

                // The whole ladder once, so that what the constraint mode chose can be checked against
                // every rung without reducing the same well over and over.
                double[] ladder = ReducedOrderTrajectory.DefaultToleranceLadder;
                ReducedOrderTrajectory[] rungs = new ReducedOrderTrajectory[ladder.Length];
                for (int r = 0; r < ladder.Length; r++)
                {
                    rungs[r] = ReducedOrderTrajectory.Reduce(
                        well.MeasuredDepths, well.Inclinations, well.Azimuths, ladder[r]);
                    Assert.That(rungs[r].IsValid, Is.True, rungs[r].FailureDescription);
                }

                foreach (double target in new[] { 5.0, 1.0, 0.5 })
                {
                    ReducedOrderTrajectory reduced = ReducedOrderTrajectory.ReduceToDeviation(
                        well.MeasuredDepths, well.Inclinations, well.Azimuths, target);
                    Assert.That(reduced.IsValid, Is.True, reduced.FailureDescription);
                    Assert.That(reduced.MaxDeviation, Is.LessThanOrEqualTo(target),
                        $"{name}: asked for {target} m, got {reduced.MaxDeviation:F4} m");

                    // The rung taken has to be the coarsest one meeting the target, so every coarser one
                    // must have missed it.
                    for (int r = 0; r < ladder.Length; r++)
                    {
                        if (ladder[r] <= reduced.AngularTolerance + 1.0e-12)
                        {
                            continue;
                        }
                        Assert.That(rungs[r].MaxDeviation, Is.GreaterThan(target),
                            $"{name} at {target} m: the coarser tolerance {ladder[r]:F6} rad would also "
                            + $"have met it, with {rungs[r].MaxDeviation:F4} m, and should have been taken.");
                    }
                    lines.Add($"{name}: within {target} m needs "
                        + $"{reduced.AngularTolerance * 180.0 / System.Math.PI:F2} deg, "
                        + $"{reduced.SectionCount} sections, achieved {reduced.MaxDeviation:F4} m");
                }
            }
            TestContext.Out.WriteLine(string.Join(System.Environment.NewLine, lines));
        }

        /// <summary>
        /// Where no rung of the ladder can meet the distance asked for, the closest one comes back rather
        /// than nothing, and it is honest about what it achieved.
        /// </summary>
        [Test]
        public void Test75ReduceToAnImpossibleDeviationReturnsTheClosest()
        {
            VectorFile file = LoadVectors();
            Dictionary<string, WellArrays> wells = LoadWells(file);
            WellArrays well = wells["2_8-N-16 T2"];

            ReducedOrderTrajectory reduced = ReducedOrderTrajectory.ReduceToDeviation(
                well.MeasuredDepths, well.Inclinations, well.Azimuths, 1.0e-6);
            Assert.That(reduced.IsValid, Is.True);
            Assert.That(reduced.MaxDeviation, Is.GreaterThan(1.0e-6));

            ReducedOrderTrajectory finest = ReducedOrderTrajectory.Reduce(
                well.MeasuredDepths, well.Inclinations, well.Azimuths,
                ReducedOrderTrajectory.DefaultToleranceLadder[0]);
            Assert.That(reduced.MaxDeviation, Is.LessThanOrEqualTo(finest.MaxDeviation + 1.0e-9),
                "The closest rung should be at least as good as the finest one.");
        }

        /// <summary>
        /// The three ways of asking where the reduced trajectory goes agree with one another, and with
        /// the metrics. Specification section 1.
        /// </summary>
        [Test]
        public void Test76QueriesAlongTheTrajectoryAgreeWithEachOther()
        {
            VectorFile file = LoadVectors();
            Dictionary<string, WellArrays> wells = LoadWells(file);
            WellArrays well = wells["2_11-A-1 A"];
            ReducedOrderTrajectory reduced = ReducedOrderTrajectory.Reduce(
                well.MeasuredDepths, well.Inclinations, well.Azimuths, 1.3 * System.Math.PI / 180.0);
            List<string> failures = new();

            Assert.That(reduced.PositionAt(reduced.StartMeasuredDepth - 1.0), Is.Null,
                "Above the first station there is no trajectory.");
            Assert.That(reduced.PositionAt(reduced.EndMeasuredDepth + 1.0), Is.Null,
                "Below the last station there is no trajectory.");
            Assert.That(reduced.TangentAt(reduced.EndMeasuredDepth + 1.0), Is.Null);

            double span = reduced.EndMeasuredDepth - reduced.StartMeasuredDepth;
            for (int n = 0; n <= 200; n++)
            {
                double measuredDepth = reduced.StartMeasuredDepth + span * n / 200.0;
                Vector3D? tangent = reduced.TangentAt(measuredDepth);
                Assert.That(tangent, Is.Not.Null, $"no tangent at {measuredDepth:F1} m");
                double length = System.Math.Sqrt(
                    (tangent!.X ?? 0.0) * (tangent.X ?? 0.0)
                    + (tangent.Y ?? 0.0) * (tangent.Y ?? 0.0)
                    + (tangent.Z ?? 0.0) * (tangent.Z ?? 0.0));
                AssertAbsolute(length, 1.0, 1.0e-12, $"tangent length at {measuredDepth:F1} m", failures);

                Assert.That(reduced.AttitudeAt(measuredDepth, out double inclination, out double azimuth),
                    Is.True);
                ReducedOrderTrajectory.TangentFromAngles(inclination, azimuth,
                    out double north, out double east, out double vertical);
                AssertAbsolute(north, tangent.X ?? 0.0, 1.0e-12, $"north at {measuredDepth:F1} m", failures);
                AssertAbsolute(east, tangent.Y ?? 0.0, 1.0e-12, $"east at {measuredDepth:F1} m", failures);
                AssertAbsolute(vertical, tangent.Z ?? 0.0, 1.0e-12, $"vertical at {measuredDepth:F1} m", failures);
                Assert.That(azimuth, Is.GreaterThanOrEqualTo(0.0).And.LessThan(2.0 * System.Math.PI));

                // The position has to move forward along the hole and no faster than the hole does.
                if (n > 0)
                {
                    Point3D? here = reduced.PositionAt(measuredDepth);
                    Point3D? before = reduced.PositionAt(measuredDepth - span / 200.0);
                    double moved = here!.Distance(before!) ?? 0.0;
                    if (moved > span / 200.0 + 1.0e-9)
                    {
                        failures.Add($"between {measuredDepth - span / 200.0:F1} and {measuredDepth:F1} m "
                            + $"the trajectory moved {moved:F4} m over {span / 200.0:F4} m of hole");
                    }
                }
            }

            // The deviation the reduction reports has to be the one a caller measures for themselves.
            double worst = 0.0;
            for (int i = 0; i < well.MeasuredDepths.Length; i++)
            {
                Point3D? position = reduced.PositionAt(well.MeasuredDepths[i]);
                int at = 3 * i;
                double north = (position!.X ?? 0.0) - well.Positions[at];
                double east = (position.Y ?? 0.0) - well.Positions[at + 1];
                double vertical = (position.Z ?? 0.0) - well.Positions[at + 2];
                worst = System.Math.Max(worst,
                    System.Math.Sqrt(north * north + east * east + vertical * vertical));
            }
            AssertAbsolute(worst, reduced.MaxDeviation, 1.0e-9, "max deviation measured by the caller", failures);

            TestContext.Out.WriteLine($"max inclination deviation "
                + $"{reduced.MaxInclinationDeviation * 180.0 / System.Math.PI:F3} deg, "
                + $"max azimuth deviation in hole "
                + $"{reduced.MaxAzimuthDeviationInHole * 180.0 / System.Math.PI:F3} deg");
            Assert.That(failures, Is.Empty, string.Join(System.Environment.NewLine, failures));
        }

        /// <summary>
        /// The edge cases the specification calls out: too few stations, stations repeating a measured
        /// depth, a hole which is vertical from end to end, and an inclination past the horizontal.
        /// </summary>
        [Test]
        public void Test77EdgeCasesAreHandled()
        {
            double tolerance = 3.0 * System.Math.PI / 180.0;

            // One station: nothing to reduce, and nothing wrong.
            ReducedOrderTrajectory single = ReducedOrderTrajectory.Reduce(
                new[] { 0.0 }, new[] { 0.0 }, new[] { 0.0 }, tolerance);
            Assert.That(single.IsValid, Is.True);
            Assert.That(single.SectionCount, Is.EqualTo(0));
            Assert.That(single.MaxDeviation, Is.EqualTo(0.0));

            // Two stations: one section, which a circular arc can always fit exactly.
            ReducedOrderTrajectory pair = ReducedOrderTrajectory.Reduce(
                new[] { 0.0, 30.0 }, new[] { 0.1, 0.2 }, new[] { 1.0, 1.1 }, tolerance);
            Assert.That(pair.IsValid, Is.True);
            Assert.That(pair.SectionCount, Is.EqualTo(1));
            Assert.That(pair.MaxDeviation, Is.LessThan(1.0e-6));

            // Three stations, the smallest case the specification calls out as still working.
            ReducedOrderTrajectory three = ReducedOrderTrajectory.Reduce(
                new[] { 0.0, 30.0, 60.0 }, new[] { 0.1, 0.2, 0.3 }, new[] { 1.0, 1.1, 1.2 }, tolerance);
            Assert.That(three.IsValid, Is.True);
            Assert.That(three.SectionCount, Is.GreaterThanOrEqualTo(1));

            // Stations repeating a measured depth are dropped, so this is the same survey as the last one.
            ReducedOrderTrajectory repeated = ReducedOrderTrajectory.Reduce(
                new[] { 0.0, 0.0, 30.0, 30.0, 60.0 },
                new[] { 0.1, 0.1, 0.2, 0.2, 0.3 },
                new[] { 1.0, 1.0, 1.1, 1.1, 1.2 }, tolerance);
            Assert.That(repeated.IsValid, Is.True);
            Assert.That(repeated.StationCount, Is.EqualTo(3));
            Assert.That(repeated.SectionCount, Is.EqualTo(three.SectionCount));

            // A hole vertical from end to end. The azimuth means nothing there, so only a hold or an arc
            // may be used, the whole of it is one straight section, and the reduction has to be exact.
            ReducedOrderTrajectory vertical = ReducedOrderTrajectory.Reduce(
                new[] { 0.0, 100.0, 500.0, 1200.0 },
                new[] { 0.0, 0.0, 0.0, 0.0 },
                new[] { 0.0, 0.0, 0.0, 0.0 }, tolerance);
            Assert.That(vertical.IsValid, Is.True);
            Assert.That(vertical.SectionCount, Is.EqualTo(1));
            Assert.That(vertical.MaxDeviation, Is.LessThan(1.0e-9));
            foreach (ReducedOrderSection section in vertical.Sections)
            {
                Assert.That(section.CurveType,
                    Is.EqualTo(ReducedOrderCurveType.Hold).Or.EqualTo(ReducedOrderCurveType.CircularArc));
            }

            // An inclination past the horizontal, which a horizontal well drilling slightly upward has.
            double[] climbing = { 0.0, 30.0, 60.0, 90.0, 120.0 };
            double[] climbingInclination =
            {
                88.0 * System.Math.PI / 180.0, 91.0 * System.Math.PI / 180.0,
                94.0 * System.Math.PI / 180.0, 97.0 * System.Math.PI / 180.0,
                100.0 * System.Math.PI / 180.0
            };
            double[] climbingAzimuth = { 0.5, 0.52, 0.54, 0.56, 0.58 };
            ReducedOrderTrajectory upward = ReducedOrderTrajectory.Reduce(
                climbing, climbingInclination, climbingAzimuth, tolerance);
            Assert.That(upward.IsValid, Is.True);
            Assert.That(upward.MaxDeviation, Is.LessThan(0.5));
            Assert.That(upward.AttitudeAt(120.0, out double endInclination, out _), Is.True);
            Assert.That(endInclination, Is.GreaterThan(System.Math.PI / 2.0),
                "The trajectory should still be climbing at its end.");

            // A survey crossing north, which needs the azimuth made continuous before it is fitted.
            double[] crossing = { 0.0, 30.0, 60.0, 90.0 };
            double[] crossingInclination = { 0.8, 0.82, 0.84, 0.86 };
            double[] crossingAzimuth =
            {
                350.0 * System.Math.PI / 180.0, 356.0 * System.Math.PI / 180.0,
                2.0 * System.Math.PI / 180.0, 8.0 * System.Math.PI / 180.0
            };
            ReducedOrderTrajectory north = ReducedOrderTrajectory.Reduce(
                crossing, crossingInclination, crossingAzimuth, tolerance);
            Assert.That(north.IsValid, Is.True);
            Assert.That(north.MaxDeviation, Is.LessThan(0.1),
                "A survey turning six degrees a stand across north is an easy fit once the azimuth is "
                + "made continuous, and an impossible one if it is not.");
        }

        /// <summary>
        /// What a caller gets back when the survey cannot be used.
        /// </summary>
        [Test]
        public void Test78UnusableSurveysAreReportedNotThrown()
        {
            double tolerance = 3.0 * System.Math.PI / 180.0;
            double[] three = { 0.0, 30.0, 60.0 };
            double[] angles = { 0.1, 0.2, 0.3 };

            Assert.Multiple(() =>
            {
                Assert.That(ReducedOrderTrajectory.Reduce(
                        System.Array.Empty<double>(), System.Array.Empty<double>(),
                        System.Array.Empty<double>(), tolerance).FailureReason,
                    Is.EqualTo(ReducedOrderFailureReason.NoStations));
                Assert.That(ReducedOrderTrajectory.Reduce(three, new[] { 0.1, 0.2 }, angles, tolerance).FailureReason,
                    Is.EqualTo(ReducedOrderFailureReason.MismatchedStationCounts));
                Assert.That(ReducedOrderTrajectory.Reduce(
                        three, new[] { 0.1, double.NaN, 0.3 }, angles, tolerance).FailureReason,
                    Is.EqualTo(ReducedOrderFailureReason.UndefinedStation));
                Assert.That(ReducedOrderTrajectory.Reduce(three, angles, angles, 0.0).FailureReason,
                    Is.EqualTo(ReducedOrderFailureReason.InvalidTolerance));
                Assert.That(ReducedOrderTrajectory.Reduce((List<SurveyPoint>?)null!, tolerance).FailureReason,
                    Is.EqualTo(ReducedOrderFailureReason.NoStations));
            });

            ReducedOrderTrajectory failed = ReducedOrderTrajectory.Reduce(three, new[] { 0.1, 0.2 }, angles, tolerance);
            Assert.That(failed.FailureDescription, Is.Not.Empty);
            Assert.That(failed.PositionAt(0.0), Is.Null);
            Assert.That(failed.TangentAt(0.0), Is.Null);
            Assert.That(failed.AttitudeAt(0.0, out _, out _), Is.False);
        }

        /// <summary>
        /// The galloping search has to test the last station of the survey when its doubling overshoots
        /// the end. Specification section 6.
        ///
        /// The search doubles its reach until a fit fails, then bisects between the last interval that
        /// held and the first that did not. Where it runs off the end of the survey instead of failing,
        /// the upper end of the bisection is the last station, which is feasible but which the bisection
        /// loop never evaluates, since it stops as soon as the two ends are adjacent. Left alone that
        /// cuts the last section short and emits one more section than necessary.
        ///
        /// The reference leaves it alone and its golden vectors carry the consequence, so the behaviour
        /// is still reachable through <see cref="ReductionOptions.ReproduceReferenceSegmentation"/> and
        /// the vector tests use it. What a caller gets is the corrected search. Four stations of
        /// perfectly straight hole are the smallest case that tells the two apart.
        /// </summary>
        [Test]
        public void Test80GallopingLeavesTheLastStationUntestedWhenItOvershoots()
        {
            double[] measuredDepths = { 0.0, 100.0, 500.0, 1200.0 };
            double[] angles = { 0.0, 0.0, 0.0, 0.0 };
            double[] tangents = new double[12];
            ReducedOrderTrajectory.TangentsFromAngles(angles, angles, tangents);
            double tolerance = 3.0 * System.Math.PI / 180.0;

            double whole = ReducedOrderTrajectory.FitSection(ReducedOrderCurveType.Hold,
                measuredDepths, tangents, angles, angles, 0, 3, out _, out _);
            Assert.That(whole, Is.LessThan(1.0e-12),
                "A hold fits a straight hole exactly over the whole survey.");

            ReducedOrderTrajectory.Segment(measuredDepths, tangents, angles, angles,
                tolerance, ReducedOrderTrajectory.DefaultMinimumSineInclination, true,
                out int[] referenceBreaks, out ReducedOrderCurveType[] referenceTypes);
            Assert.That(referenceTypes.Length, Is.EqualTo(2),
                "The reference search stops at station 2 and emits a second section.");
            Assert.That(referenceBreaks, Is.EqualTo(new[] { 0, 2, 3 }));

            ReducedOrderTrajectory.Segment(measuredDepths, tangents, angles, angles,
                tolerance, ReducedOrderTrajectory.DefaultMinimumSineInclination, false,
                out int[] breaks, out ReducedOrderCurveType[] types);
            Assert.That(types.Length, Is.EqualTo(1),
                "The corrected search covers the whole survey with the one section that fits it.");
            Assert.That(breaks, Is.EqualTo(new[] { 0, 3 }));
            Assert.That(types[0], Is.EqualTo(ReducedOrderCurveType.Hold));
        }

        /// <summary>
        /// Correcting the galloping search takes sections out without costing accuracy.
        ///
        /// Fewer sections means fewer parameters for the refinement to move, so a shorter answer could in
        /// principle be a worse one. It is not: the section the correction removes is the one the search
        /// had no reason to cut, and the curve covering both halves fits the stations of both, so the
        /// accuracy is the same to within the noise of a restart. This is measured rather than assumed,
        /// on the two long wells of the vector set at every tolerance the vectors cover.
        /// </summary>
        [Test]
        public void Test81CorrectedSegmentationCostsNoAccuracy()
        {
            VectorFile file = LoadVectors();
            Dictionary<string, WellArrays> wells = LoadWells(file);
            List<string> lines = new();
            List<string> failures = new();
            int saved = 0;

            foreach (string name in new[] { "2_8-N-16 T2", "2_11-A-1 A" })
            {
                WellArrays well = wells[name];
                foreach (double degrees in new[] { 0.5, 1.3, 3.0 })
                {
                    double tolerance = degrees * System.Math.PI / 180.0;
                    ReducedOrderTrajectory reference = ReducedOrderTrajectory.Reduce(
                        well.MeasuredDepths, well.Inclinations, well.Azimuths, tolerance,
                        new ReductionOptions() { ReproduceReferenceSegmentation = true });
                    ReducedOrderTrajectory corrected = ReducedOrderTrajectory.Reduce(
                        well.MeasuredDepths, well.Inclinations, well.Azimuths, tolerance);

                    Assert.That(corrected.SectionCount, Is.LessThanOrEqualTo(reference.SectionCount),
                        $"{name} at {degrees} deg: the correction added a section.");
                    saved += reference.SectionCount - corrected.SectionCount;

                    // Every section still has to hold the angular tolerance it was cut at: the corrected
                    // search may only lengthen a section to an interval its own fit covers.
                    ReducedOrderTrajectory.Segment(well.MeasuredDepths, well.Tangents, well.Inclinations,
                        well.Azimuths, tolerance, ReducedOrderTrajectory.DefaultMinimumSineInclination,
                        false, out int[] breaks, out ReducedOrderCurveType[] types);
                    for (int q = 0; q < types.Length; q++)
                    {
                        double residual = ReducedOrderTrajectory.FitSection(types[q],
                            well.MeasuredDepths, well.Tangents, well.Inclinations, well.Azimuths,
                            breaks[q], breaks[q + 1], out _, out _);
                        if (residual > tolerance)
                        {
                            failures.Add($"{name} at {degrees} deg: section {q} of the corrected cut "
                                + $"leaves {residual:E3} rad, over the {tolerance:E3} rad asked for.");
                        }
                    }

                    // The deviation may drift a little either way, because the refinement is restarted
                    // from random perturbations, but it must not get materially worse.
                    double allowed = System.Math.Max(1.25 * reference.MaxDeviation,
                        reference.MaxDeviation + 0.05);
                    if (corrected.MaxDeviation > allowed)
                    {
                        failures.Add($"{name} at {degrees} deg: the corrected cut deviates "
                            + $"{corrected.MaxDeviation:F4} m against {reference.MaxDeviation:F4} m.");
                    }
                    lines.Add($"{name} at {degrees} deg: {reference.SectionCount} sections "
                        + $"({reference.MaxDeviation:F4} m) becomes {corrected.SectionCount} "
                        + $"({corrected.MaxDeviation:F4} m)");
                }
            }
            TestContext.Out.WriteLine(string.Join(System.Environment.NewLine, lines));
            TestContext.Out.WriteLine($"sections saved in total: {saved}");
            Assert.That(saved, Is.GreaterThan(0), "The correction should be removing sections.");
            Assert.That(failures, Is.Empty, string.Join(System.Environment.NewLine, failures));
        }

        /// <summary>
        /// Reducing a list of survey points, which is how the rest of this library carries a survey. The
        /// position of the first point is taken as the origin, so positions come back where the caller
        /// expects them rather than at zero.
        /// </summary>
        [Test]
        public void Test79ReducingAListOfSurveyPointsKeepsTheCallersFrame()
        {
            VectorFile file = LoadVectors();
            Dictionary<string, WellArrays> wells = LoadWells(file);
            WellArrays well = wells["2_8-N-16 T2"];
            double tolerance = 3.0 * System.Math.PI / 180.0;

            List<SurveyPoint> survey = new();
            for (int i = 0; i < well.MeasuredDepths.Length; i++)
            {
                survey.Add(new SurveyPoint()
                {
                    MD = well.MeasuredDepths[i],
                    Inclination = well.Inclinations[i],
                    Azimuth = well.Azimuths[i],
                    X = 1000.0 + well.Positions[3 * i],
                    Y = 2000.0 + well.Positions[3 * i + 1],
                    Z = 30.0 + well.Positions[3 * i + 2]
                });
            }

            ReducedOrderTrajectory fromPoints = ReducedOrderTrajectory.Reduce(survey, tolerance);
            ReducedOrderTrajectory fromArrays = ReducedOrderTrajectory.Reduce(
                well.MeasuredDepths, well.Inclinations, well.Azimuths, tolerance);

            Assert.That(fromPoints.IsValid, Is.True, fromPoints.FailureDescription);
            Assert.That(fromPoints.SectionCount, Is.EqualTo(fromArrays.SectionCount));
            Assert.That(fromPoints.MaxDeviation, Is.EqualTo(fromArrays.MaxDeviation).Within(1.0e-12));
            Assert.That(fromPoints.Origin.X, Is.EqualTo(1000.0).Within(1.0e-9));

            // The reduced trajectory has to sit within its own stated deviation of the survey it came
            // from, in the caller's own frame.
            double worst = 0.0;
            for (int i = 0; i < survey.Count; i++)
            {
                Point3D? position = fromPoints.PositionAt(survey[i].MD!.Value);
                worst = System.Math.Max(worst, position!.Distance(survey[i])!.Value);
            }
            Assert.That(worst, Is.EqualTo(fromPoints.MaxDeviation).Within(1.0e-9));
        }

        // ------------------------------------------------------------------ well inputs

        private class WellArrays
        {
            internal double[] MeasuredDepths = System.Array.Empty<double>();
            internal double[] Inclinations = System.Array.Empty<double>();
            internal double[] Azimuths = System.Array.Empty<double>();
            internal double[] Tangents = System.Array.Empty<double>();
            internal double[] Positions = System.Array.Empty<double>();
        }

        private static Dictionary<string, WellArrays> LoadWells(VectorFile file)
        {
            Dictionary<string, WellArrays> wells = new();
            foreach (WellCase one in file.WellInputs!)
            {
                WellArrays arrays = new()
                {
                    MeasuredDepths = one.Md!.ToArray(),
                    Inclinations = one.Inclination!.ToArray(),
                    Azimuths = one.Azimuth!.ToArray()
                };
                arrays.Tangents = new double[3 * arrays.MeasuredDepths.Length];
                ReducedOrderTrajectory.TangentsFromAngles(arrays.Inclinations, arrays.Azimuths, arrays.Tangents);
                arrays.Positions = new double[3 * arrays.MeasuredDepths.Length];
                ReducedOrderTrajectory.MinimumCurvature(arrays.MeasuredDepths, arrays.Tangents, arrays.Positions);
                wells[one.Well!] = arrays;
            }
            return wells;
        }

        // ------------------------------------------------------------------ vector file shape

        private class VectorFile
        {
            [JsonPropertyName("description")] public string? Description { get; set; }
            [JsonPropertyName("curveTypes")] public CurveTypeMap? CurveTypes { get; set; }
            [JsonPropertyName("minSinTheta")] public double MinSinTheta { get; set; }
            [JsonPropertyName("tangentFromAngles")] public List<TangentCase>? TangentFromAngles { get; set; }
            [JsonPropertyName("orthoBasis")] public List<BasisCase>? OrthoBasis { get; set; }
            [JsonPropertyName("minimumCurvature")] public MinimumCurvatureCase? MinimumCurvature { get; set; }
            [JsonPropertyName("sectionTangents")] public List<SectionCase>? SectionTangents { get; set; }
            [JsonPropertyName("rotAlign")] public List<RotationCase>? RotAlign { get; set; }
            [JsonPropertyName("wellInputs")] public List<WellCase>? WellInputs { get; set; }
            [JsonPropertyName("closedFormFits")] public List<FitCase>? ClosedFormFits { get; set; }
            [JsonPropertyName("segmentation")] public List<SegmentationCase>? Segmentation { get; set; }
            [JsonPropertyName("endToEnd")] public List<EndToEndCase>? EndToEnd { get; set; }
        }

        private class EndToEndCase
        {
            [JsonPropertyName("well")] public string? Well { get; set; }
            [JsonPropertyName("toleranceDeg")] public double ToleranceDeg { get; set; }
            [JsonPropertyName("stationCount")] public int StationCount { get; set; }
            [JsonPropertyName("sectionCount")] public int SectionCount { get; set; }
            [JsonPropertyName("types")] public List<int>? Types { get; set; }
            [JsonPropertyName("breaks")] public List<int>? Breaks { get; set; }
            [JsonPropertyName("referenceMaxDeviation")] public double ReferenceMaxDeviation { get; set; }
            [JsonPropertyName("referenceRmsDeviation")] public double ReferenceRmsDeviation { get; set; }
            [JsonPropertyName("initialInclination")] public double InitialInclination { get; set; }
            [JsonPropertyName("initialAzimuth")] public double InitialAzimuth { get; set; }
            [JsonPropertyName("parameters")] public List<double>? Parameters { get; set; }
            [JsonPropertyName("sampleStationIndices")] public List<int>? SampleStationIndices { get; set; }
            [JsonPropertyName("referencePositionsAtSamples")] public List<List<double>>? ReferencePositionsAtSamples { get; set; }
            [JsonPropertyName("originalPositionsAtSamples")] public List<List<double>>? OriginalPositionsAtSamples { get; set; }
        }

        private class WellCase
        {
            [JsonPropertyName("well")] public string? Well { get; set; }
            [JsonPropertyName("stationCount")] public int StationCount { get; set; }
            [JsonPropertyName("md")] public List<double>? Md { get; set; }
            [JsonPropertyName("inclination")] public List<double>? Inclination { get; set; }
            [JsonPropertyName("azimuth")] public List<double>? Azimuth { get; set; }
        }

        private class FitCase
        {
            [JsonPropertyName("well")] public string? Well { get; set; }
            [JsonPropertyName("i")] public int I { get; set; }
            [JsonPropertyName("j")] public int J { get; set; }
            [JsonPropertyName("curveType")] public int CurveType { get; set; }
            [JsonPropertyName("p1")] public double P1 { get; set; }
            [JsonPropertyName("p2")] public double P2 { get; set; }
            [JsonPropertyName("maxAngularResidual")] public double MaxAngularResidual { get; set; }
        }

        private class SegmentationCase
        {
            [JsonPropertyName("well")] public string? Well { get; set; }
            [JsonPropertyName("toleranceDeg")] public double ToleranceDeg { get; set; }
            [JsonPropertyName("breaks")] public List<int>? Breaks { get; set; }
            [JsonPropertyName("types")] public List<int>? Types { get; set; }
            [JsonPropertyName("sectionCount")] public int SectionCount { get; set; }
        }

        private class CurveTypeMap
        {
            [JsonPropertyName("Hold")] public int Hold { get; set; }
            [JsonPropertyName("CircularArc")] public int CircularArc { get; set; }
            [JsonPropertyName("ConstantToolface")] public int ConstantToolface { get; set; }
            [JsonPropertyName("ConstantBuildTurn")] public int ConstantBuildTurn { get; set; }
        }

        private class TangentCase
        {
            [JsonPropertyName("inclination")] public double Inclination { get; set; }
            [JsonPropertyName("azimuth")] public double Azimuth { get; set; }
            [JsonPropertyName("tangent")] public List<double>? Tangent { get; set; }
        }

        private class BasisCase
        {
            [JsonPropertyName("t0")] public List<double>? T0 { get; set; }
            [JsonPropertyName("e1")] public List<double>? E1 { get; set; }
            [JsonPropertyName("e2")] public List<double>? E2 { get; set; }
        }

        private class MinimumCurvatureCase
        {
            [JsonPropertyName("md")] public List<double>? Md { get; set; }
            [JsonPropertyName("inclination")] public List<double>? Inclination { get; set; }
            [JsonPropertyName("azimuth")] public List<double>? Azimuth { get; set; }
            [JsonPropertyName("tangents")] public List<List<double>>? Tangents { get; set; }
            [JsonPropertyName("positions")] public List<List<double>>? Positions { get; set; }
        }

        private class SectionCase
        {
            [JsonPropertyName("t0Name")] public string? T0Name { get; set; }
            [JsonPropertyName("t0")] public List<double>? T0 { get; set; }
            [JsonPropertyName("curveType")] public int CurveType { get; set; }
            [JsonPropertyName("curveTypeName")] public string? CurveTypeName { get; set; }
            [JsonPropertyName("p1")] public double P1 { get; set; }
            [JsonPropertyName("p2")] public double P2 { get; set; }
            [JsonPropertyName("u")] public List<double>? U { get; set; }
            [JsonPropertyName("tangents")] public List<List<double>>? Tangents { get; set; }
        }

        private class RotationCase
        {
            [JsonPropertyName("a")] public List<double>? A { get; set; }
            [JsonPropertyName("b")] public List<double>? B { get; set; }
            [JsonPropertyName("R")] public List<List<double>>? R { get; set; }
            [JsonPropertyName("Ra")] public List<double>? Ra { get; set; }
        }
    }
}
